# Generated by Django 6.0.3 on 2026-03-15 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name': 'Сотрудник', 'verbose_name_plural': 'Сотрудники'},
        ),
        migrations.AlterModelOptions(
            name='labortimelog',
            options={'ordering': ['-date'], 'verbose_name': 'Трудозатраты', 'verbose_name_plural': 'Трудозатраты'},
        ),
        migrations.AlterModelOptions(
            name='materialbatch',
            options={'ordering': ['-date'], 'verbose_name': 'Движение по материалу', 'verbose_name_plural': 'Движения по материалам'},
        ),
        migrations.AlterModelOptions(
            name='operationtype',
            options={'verbose_name': 'Тип операции', 'verbose_name_plural': 'Типы операций'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at'], 'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': 'Позиция заказа', 'verbose_name_plural': 'Позиции заказа'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Изделие', 'verbose_name_plural': 'Изделия'},
        ),
        migrations.AlterModelOptions(
            name='productionbatch',
            options={'verbose_name': 'Производственная партия', 'verbose_name_plural': 'Производственные партии'},
        ),
        migrations.AlterModelOptions(
            name='productionmaterialusage',
            options={'verbose_name': 'Расход материала', 'verbose_name_plural': 'Расход материалов'},
        ),
        migrations.AlterModelOptions(
            name='productlabor',
            options={'verbose_name': 'Норма времени по операции', 'verbose_name_plural': 'Нормы времени по операциям'},
        ),
        migrations.AlterModelOptions(
            name='productmaterial',
            options={'verbose_name': 'Материал изделия', 'verbose_name_plural': 'Материалы изделия'},
        ),
        migrations.AlterField(
            model_name='employee',
            name='full_name',
            field=models.CharField(max_length=255, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='hourly_rate',
            field=models.DecimalField(decimal_places=2, help_text='Ставка за час работы сотрудника', max_digits=10, verbose_name='Часовая ставка'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.CharField(blank=True, max_length=100, verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='labortimelog',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labor_logs', to='core.productionbatch', verbose_name='Партия'),
        ),
        migrations.AlterField(
            model_name='labortimelog',
            name='comment',
            field=models.CharField(blank=True, max_length=255, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='labortimelog',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='labortimelog',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.employee', verbose_name='Сотрудник'),
        ),
        migrations.AlterField(
            model_name='labortimelog',
            name='minutes_spent',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Затраченное время (мин)'),
        ),
        migrations.AlterField(
            model_name='labortimelog',
            name='operation_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.operationtype', verbose_name='Операция'),
        ),
        migrations.AlterField(
            model_name='material',
            name='current_stock',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='Текущий остаток'),
        ),
        migrations.AlterField(
            model_name='material',
            name='material_type',
            field=models.CharField(blank=True, max_length=100, verbose_name='Тип материала'),
        ),
        migrations.AlterField(
            model_name='material',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='material',
            name='unit',
            field=models.CharField(help_text='Единица измерения (лист, м2, м, кг и т.п.)', max_length=50, verbose_name='Ед. измерения'),
        ),
        migrations.AlterField(
            model_name='materialbatch',
            name='comment',
            field=models.CharField(blank=True, max_length=255, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='materialbatch',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='materialbatch',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='core.material', verbose_name='Материал'),
        ),
        migrations.AlterField(
            model_name='materialbatch',
            name='movement_type',
            field=models.CharField(choices=[('IN', 'Поступление'), ('OUT', 'Списание'), ('ADJ', 'Корректировка')], default='IN', max_length=3, verbose_name='Тип движения'),
        ),
        migrations.AlterField(
            model_name='materialbatch',
            name='quantity',
            field=models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='materialbatch',
            name='unit_price',
            field=models.DecimalField(decimal_places=4, help_text='Цена за единицу в момент движения', max_digits=12, verbose_name='Цена за единицу'),
        ),
        migrations.AlterField(
            model_name='operationtype',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='operationtype',
            name='hourly_rate',
            field=models.DecimalField(decimal_places=2, help_text='Ставка за час работы для этого типа операции', max_digits=10, verbose_name='Ставка за час'),
        ),
        migrations.AlterField(
            model_name='operationtype',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название операции'),
        ),
        migrations.AlterField(
            model_name='order',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_name',
            field=models.CharField(help_text='Имя или название клиента', max_length=255, verbose_name='Клиент'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('NEW', 'Новый'), ('INP', 'В работе'), ('DON', 'Завершен'), ('CNL', 'Отменен')], default='NEW', max_length=3, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.order', verbose_name='Заказ'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='planned_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Цена продажи за единицу (может отличаться от плановой в карточке изделия)', max_digits=12, null=True, verbose_name='Цена продажи за единицу'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.product', verbose_name='Изделие'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.PositiveIntegerField(verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, max_length=100, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='product',
            name='planned_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Плановая цена продажи за единицу', max_digits=12, null=True, verbose_name='Плановая цена продажи'),
        ),
        migrations.AlterField(
            model_name='productionbatch',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Окончание'),
        ),
        migrations.AlterField(
            model_name='productionbatch',
            name='order_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batches', to='core.orderitem', verbose_name='Позиция заказа'),
        ),
        migrations.AlterField(
            model_name='productionbatch',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batches', to='core.product', verbose_name='Изделие'),
        ),
        migrations.AlterField(
            model_name='productionbatch',
            name='quantity_planned',
            field=models.PositiveIntegerField(verbose_name='Плановое количество'),
        ),
        migrations.AlterField(
            model_name='productionbatch',
            name='quantity_produced',
            field=models.PositiveIntegerField(default=0, verbose_name='Фактическое количество'),
        ),
        migrations.AlterField(
            model_name='productionbatch',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Начало'),
        ),
        migrations.AlterField(
            model_name='productionmaterialusage',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_usages', to='core.productionbatch', verbose_name='Партия'),
        ),
        migrations.AlterField(
            model_name='productionmaterialusage',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.material', verbose_name='Материал'),
        ),
        migrations.AlterField(
            model_name='productionmaterialusage',
            name='quantity',
            field=models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='productlabor',
            name='minutes_per_unit',
            field=models.DecimalField(decimal_places=2, help_text='Норма времени (в минутах) на 1 изделие', max_digits=8, verbose_name='Время на 1 изделие (мин)'),
        ),
        migrations.AlterField(
            model_name='productlabor',
            name='operation_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.operationtype', verbose_name='Тип операции'),
        ),
        migrations.AlterField(
            model_name='productlabor',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labor_norms', to='core.product', verbose_name='Изделие'),
        ),
        migrations.AlterField(
            model_name='productmaterial',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.material', verbose_name='Материал'),
        ),
        migrations.AlterField(
            model_name='productmaterial',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='core.product', verbose_name='Изделие'),
        ),
        migrations.AlterField(
            model_name='productmaterial',
            name='quantity_per_unit',
            field=models.DecimalField(decimal_places=4, help_text='Норма расхода материала на 1 изделие', max_digits=12, verbose_name='Расход на 1 изделие'),
        ),
    ]
