# Generated by Django 6.0.3 on 2026-03-15 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_material_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='CuttingSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Лист для резки',
                'verbose_name_plural': 'Листы для резки',
            },
        ),
    ]
