# Generated by Django 6.0.3 on 2026-03-15 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_cuttingsheet'),
    ]

    def create_cutting_sheets(apps, schema_editor):
        CuttingSheet = apps.get_model('core', 'CuttingSheet')
        defaults = [
            "Лист для резки шлифованный",
            "Лист для резки грунтованный",
            "Лист для резки тонированный",
        ]
        for name in defaults:
            CuttingSheet.objects.get_or_create(name=name)

    def remove_cutting_sheets(apps, schema_editor):
        CuttingSheet = apps.get_model('core', 'CuttingSheet')
        CuttingSheet.objects.filter(
            name__in=[
                "Лист для резки шлифованный",
                "Лист для резки грунтованный",
                "Лист для резки тонированный",
            ]
        ).delete()

    operations = [
        migrations.RunPython(create_cutting_sheets, remove_cutting_sheets),
    ]
