# Generated by Django 6.0.3 on 2026-03-15 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_add_default_cutting_sheets"),
    ]

    def forwards_func(apps, schema_editor):
        CuttingSheet = apps.get_model("core", "CuttingSheet")
        Material = apps.get_model("core", "Material")
        for sheet in CuttingSheet.objects.all():
            Material.objects.get_or_create(
                name=sheet.name,
                defaults={
                    "material_type": "Лист для резки",
                    "unit": "лист",
                    "current_stock": 0,
                },
            )

    def reverse_func(apps, schema_editor):
        Material = apps.get_model("core", "Material")
        Material.objects.filter(
            material_type="Лист для резки",
            name__in=[
                "Лист для резки шлифованный",
                "Лист для резки грунтованный",
                "Лист для резки тонированный",
            ],
        ).delete()

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]
