# Generated by Django 6.0.3 on 2026-03-15 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_move_cutting_sheets_to_materials'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CuttingSheet',
        ),
    ]
