# Generated by Django 6.0.3 on 2026-03-15 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_delete_cuttingsheet'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='thickness_mm',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Толщина в миллиметрах', max_digits=8, null=True, verbose_name='Толщина (мм)'),
        ),
    ]
