# Generated by Django 6.0.3 on 2026-03-15 17:37

from decimal import Decimal

from django.db import migrations


def add_plywood_materials(apps, schema_editor):
    Material = apps.get_model("core", "Material")
    materials = [
        {"name": "Фанера ФК 900*600 сорт 2/2", "thickness_mm": Decimal("6")},
        {"name": "Фанера ФК 621*621 сорт 2/2", "thickness_mm": Decimal("6")},
        {"name": "Фанера ФК 317*900 сорт 2/2", "thickness_mm": Decimal("6")},
    ]
    for m in materials:
        Material.objects.get_or_create(
            name=m["name"],
            defaults={
                "material_type": "Фанера ФК",
                "thickness_mm": m["thickness_mm"],
                "unit": "лист",
                "current_stock": 0,
            },
        )


def remove_plywood_materials(apps, schema_editor):
    Material = apps.get_model("core", "Material")
    Material.objects.filter(
        name__in=[
            "Фанера ФК 900*600 сорт 2/2",
            "Фанера ФК 621*621 сорт 2/2",
            "Фанера ФК 317*900 сорт 2/2",
        ]
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_add_material_thickness"),
    ]

    operations = [
        migrations.RunPython(add_plywood_materials, remove_plywood_materials),
    ]
