# Generated by Django 6.0.3 on 2026-03-15 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_add_material_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='materials/', verbose_name='Фото'),
        ),
    ]
