# Generated by Django 6.0.3 on 2026-03-15 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_add_material_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('product', models.ForeignKey(blank=True, help_text='Изделие, для которого составлена карта (необязательно)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tech_cards', to='core.product', verbose_name='Изделие')),
            ],
            options={
                'verbose_name': 'Технологическая карта',
                'verbose_name_plural': 'Технологические карты',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TechCardItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=4, help_text='Норма расхода на одно изделие (в ед. измерения материала)', max_digits=12, verbose_name='Количество на единицу')),
                ('item_kind', models.CharField(choices=[('component', 'Комплектующие'), ('raw', 'Сырьё'), ('material', 'Материал')], default='material', max_length=20, verbose_name='Тип позиции')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='Примечание')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.material', verbose_name='Материал / позиция')),
                ('tech_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.techcard', verbose_name='Технологическая карта')),
            ],
            options={
                'verbose_name': 'Позиция технологической карты',
                'verbose_name_plural': 'Позиции технологической карты',
                'ordering': ['item_kind', 'material__name'],
                'unique_together': {('tech_card', 'material')},
            },
        ),
    ]
