# Generated by Django 6.0.3 on 2026-03-15 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_add_tech_card'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Организация',
                'verbose_name_plural': 'Организации',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TechOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('completed', 'Проведён')], default='draft', max_length=20, verbose_name='Статус')),
                ('production_cost', models.DecimalField(decimal_places=2, default=0, help_text='Дополнительные затраты (труд, энергия и т.п.), включаются в себестоимость', max_digits=12, verbose_name='Затраты на производство')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Дата')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tech_operations', to='core.organization', verbose_name='Организация')),
                ('tech_card', models.ForeignKey(blank=True, help_text='Заполнить состав из техкарты или ввести вручную', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tech_operations', to='core.techcard', verbose_name='Техкарта')),
            ],
            options={
                'verbose_name': 'Технологическая операция',
                'verbose_name_plural': 'Технологические операции',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TechOperationProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='Количество')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.product', verbose_name='Изделие')),
                ('tech_operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='core.techoperation', verbose_name='Технологическая операция')),
            ],
            options={
                'verbose_name': 'Продукция техоперации',
                'verbose_name_plural': 'Продукция техопераций',
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warehouses', to='core.organization', verbose_name='Организация')),
            ],
            options={
                'verbose_name': 'Склад',
                'verbose_name_plural': 'Склады',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='techoperation',
            name='material_warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tech_ops_material', to='core.warehouse', verbose_name='Склад для материалов'),
        ),
        migrations.AddField(
            model_name='techoperation',
            name='product_warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tech_ops_product', to='core.warehouse', verbose_name='Склад для продукции'),
        ),
        migrations.CreateModel(
            name='TechOperationMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='Количество')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.material', verbose_name='Материал')),
                ('tech_operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='core.techoperation', verbose_name='Технологическая операция')),
            ],
            options={
                'verbose_name': 'Материал техоперации',
                'verbose_name_plural': 'Материалы техопераций',
                'unique_together': {('tech_operation', 'material')},
            },
        ),
        migrations.CreateModel(
            name='ProductStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='Количество')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouse_stocks', to='core.product', verbose_name='Изделие')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_stocks', to='core.warehouse', verbose_name='Склад')),
            ],
            options={
                'verbose_name': 'Остаток продукции на складе',
                'verbose_name_plural': 'Остатки продукции на складах',
                'ordering': ['warehouse', 'product__name'],
                'unique_together': {('warehouse', 'product')},
            },
        ),
        migrations.CreateModel(
            name='MaterialStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='Количество')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouse_stocks', to='core.material', verbose_name='Материал')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_stocks', to='core.warehouse', verbose_name='Склад')),
            ],
            options={
                'verbose_name': 'Остаток материала на складе',
                'verbose_name_plural': 'Остатки материалов на складах',
                'ordering': ['warehouse', 'material__name'],
                'unique_together': {('warehouse', 'material')},
            },
        ),
    ]
