# Generated by Django 6.0.3 on 2026-03-15 19:07

from django.db import migrations


def create_defaults(apps, schema_editor):
    Organization = apps.get_model("core", "Organization")
    Warehouse = apps.get_model("core", "Warehouse")
    org, _ = Organization.objects.get_or_create(
        name="Основная",
        defaults={},
    )
    Warehouse.objects.get_or_create(
        name="Основной склад",
        defaults={"organization_id": org.pk},
    )


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_add_tech_operation_warehouses"),
    ]

    operations = [
        migrations.RunPython(create_defaults, noop),
    ]
