# Generated by Django 6.0.3 on 2026-03-15 19:08

from django.db import migrations


def sync_stock(apps, schema_editor):
    Warehouse = apps.get_model("core", "Warehouse")
    Material = apps.get_model("core", "Material")
    MaterialStock = apps.get_model("core", "MaterialStock")
    try:
        wh = Warehouse.objects.get(name="Основной склад")
    except Warehouse.DoesNotExist:
        return
    for m in Material.objects.all():
        MaterialStock.objects.get_or_create(
            warehouse=wh,
            material=m,
            defaults={"quantity": m.current_stock},
        )


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_add_default_org_warehouse"),
    ]

    operations = [
        migrations.RunPython(sync_stock, noop),
    ]
