# Generated by Django 6.0.3 on 2026-03-15 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_operation_type_hourly_rate_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operationtype',
            name='hourly_rate',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Ставка за час работы для этого типа операции', max_digits=10, verbose_name='Ставка за час'),
        ),
    ]
