# Generated by Django 6.0.3 on 2026-03-15 19:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_operation_type_hourly_rate_blank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labortimelog',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='labor_logs', to='core.productionbatch', verbose_name='Партия'),
        ),
        migrations.CreateModel(
            name='ProductionAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('in_progress', 'В работе'), ('completed', 'Выполнено'), ('cancelled', 'Отменено')], default='draft', max_length=20, verbose_name='Статус')),
                ('date_planned', models.DateField(blank=True, null=True, verbose_name='Плановая дата')),
                ('date_started', models.DateTimeField(blank=True, null=True, verbose_name='Дата начала')),
                ('date_completed', models.DateTimeField(blank=True, null=True, verbose_name='Дата завершения')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('material_warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_assignments_material', to='core.warehouse', verbose_name='Склад материалов')),
                ('product_warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_assignments_product', to='core.warehouse', verbose_name='Склад для продукции')),
            ],
            options={
                'verbose_name': 'Производственное задание',
                'verbose_name_plural': 'Производственные задания',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='labortimelog',
            name='production_assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='labor_logs', to='core.productionassignment', verbose_name='Производственное задание'),
        ),
        migrations.CreateModel(
            name='ProductionAssignmentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_planned', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='Плановое количество')),
                ('quantity_produced', models.DecimalField(decimal_places=4, default=0, max_digits=12, verbose_name='Фактически выпущено')),
                ('sequence', models.PositiveSmallIntegerField(default=1, help_text='Порядок выполнения (для последовательного списания)', verbose_name='Номер этапа')),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('in_progress', 'В работе'), ('completed', 'Выполнено')], default='pending', max_length=20, verbose_name='Статус этапа')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Начало этапа')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Окончание этапа')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.productionassignment', verbose_name='Производственное задание')),
                ('tech_card', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignment_items', to='core.techcard', verbose_name='Техкарта')),
            ],
            options={
                'verbose_name': 'Позиция производственного задания',
                'verbose_name_plural': 'Позиции производственного задания',
                'ordering': ['assignment', 'sequence', 'pk'],
            },
        ),
        migrations.AddField(
            model_name='labortimelog',
            name='production_assignment_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='labor_logs', to='core.productionassignmentitem', verbose_name='Позиция задания (этап)'),
        ),
        migrations.AddField(
            model_name='techoperation',
            name='production_assignment_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tech_operations', to='core.productionassignmentitem', verbose_name='Позиция производственного задания'),
        ),
        migrations.CreateModel(
            name='ProductionDeviation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='Количество')),
                ('deviation_type', models.CharField(choices=[('defect', 'Брак'), ('overuse', 'Перерасход'), ('saving', 'Экономия')], max_length=20, verbose_name='Тип отклонения')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deviations', to='core.productionassignment', verbose_name='Производственное задание')),
                ('assignment_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deviations', to='core.productionassignmentitem', verbose_name='Позиция задания')),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.material', verbose_name='Материал')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.product', verbose_name='Изделие')),
            ],
            options={
                'verbose_name': 'Отклонение в производстве',
                'verbose_name_plural': 'Отклонения в производстве',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductionOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=4, help_text='Количество по норме техкарты', max_digits=12, verbose_name='Объём производства')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('reserved', 'Материалы зарезервированы'), ('in_progress', 'В производстве'), ('completed', 'Выполнен'), ('cancelled', 'Отменён')], default='draft', max_length=20, verbose_name='Статус')),
                ('date_planned', models.DateField(blank=True, null=True, verbose_name='Плановая дата')),
                ('date_deadline', models.DateField(blank=True, null=True, verbose_name='Срок выполнения')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('material_warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_orders_material', to='core.warehouse', verbose_name='Склад материалов')),
                ('product_warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_orders_product', to='core.warehouse', verbose_name='Склад для продукции')),
                ('tech_card', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_orders', to='core.techcard', verbose_name='Техкарта')),
            ],
            options={
                'verbose_name': 'Заказ на производство',
                'verbose_name_plural': 'Заказы на производство',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='techoperation',
            name='production_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tech_operations', to='core.productionorder', verbose_name='Заказ на производство'),
        ),
        migrations.CreateModel(
            name='MaterialReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='Количество')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.material', verbose_name='Материал')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.warehouse', verbose_name='Склад')),
                ('production_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='core.productionorder', verbose_name='Заказ на производство')),
            ],
            options={
                'verbose_name': 'Резерв материала',
                'verbose_name_plural': 'Резервы материалов',
                'unique_together': {('production_order', 'material')},
            },
        ),
    ]
