# Generated by Django 6.0.3 on 2026-03-15 20:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_production_planning'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('sequence', models.PositiveSmallIntegerField(default=1, verbose_name='Порядок')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Этап производства',
                'verbose_name_plural': 'Этапы производства',
                'ordering': ['sequence', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TechProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Техпроцесс',
                'verbose_name_plural': 'Техпроцессы',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='user',
            field=models.OneToOneField(blank=True, help_text='Для входа в веб-приложение и просмотра своей работы и зарплаты', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.CreateModel(
            name='ProductDisassembly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='Количество к разбору')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('completed', 'Проведён')], default='draft', max_length=20, verbose_name='Статус')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Дата')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('material_warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='disassemblies_to', to='core.warehouse', verbose_name='Склад материалов (куда)')),
                ('product_warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='disassemblies_from', to='core.warehouse', verbose_name='Склад продукции (откуда)')),
                ('tech_card', models.ForeignKey(help_text='Состав разбора берётся из техкарты изделия', on_delete=django.db.models.deletion.PROTECT, related_name='disassemblies', to='core.techcard', verbose_name='Техкарта')),
            ],
            options={
                'verbose_name': 'Разбор изделия',
                'verbose_name_plural': 'Разбор изделий',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='productionassignmentitem',
            name='production_stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignment_items', to='core.productionstage', verbose_name='Этап производства'),
        ),
        migrations.AddField(
            model_name='productionassignment',
            name='tech_process',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments', to='core.techprocess', verbose_name='Техпроцесс'),
        ),
        migrations.CreateModel(
            name='TechProcessStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=1, verbose_name='Порядок')),
                ('production_stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.productionstage', verbose_name='Этап производства')),
                ('tech_process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.techprocess', verbose_name='Техпроцесс')),
            ],
            options={
                'verbose_name': 'Этап техпроцесса',
                'verbose_name_plural': 'Этапы техпроцесса',
                'ordering': ['tech_process', 'order'],
                'unique_together': {('tech_process', 'production_stage')},
            },
        ),
        migrations.AddField(
            model_name='techprocess',
            name='stages',
            field=models.ManyToManyField(blank=True, related_name='tech_processes', through='core.TechProcessStage', through_fields=('tech_process', 'production_stage'), to='core.productionstage', verbose_name='Этапы'),
        ),
    ]
