# Generated by Django 6.0.3 on 2026-03-15 20:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_stages_disassembly_employee'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='techcarditem',
            options={'ordering': ['item_kind', 'material__name', 'product__name'], 'verbose_name': 'Позиция технологической карты', 'verbose_name_plural': 'Позиции технологической карты'},
        ),
        migrations.AlterUniqueTogether(
            name='techcarditem',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='productionassignment',
            name='supply_assignment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplies_main_assignment', to='core.productionassignment', verbose_name='Задание снабжения (полуфабрикаты)'),
        ),
        migrations.AddField(
            model_name='techcarditem',
            name='product',
            field=models.ForeignKey(blank=True, help_text='Изделие (полуфабрикат), расходуемое по норме на единицу', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tech_card_items_as_component', to='core.product', verbose_name='Полуфабрикат / изделие'),
        ),
        migrations.AlterField(
            model_name='techcarditem',
            name='item_kind',
            field=models.CharField(choices=[('component', 'Комплектующие / полуфабрикат'), ('raw', 'Сырьё'), ('material', 'Материал')], default='material', max_length=20, verbose_name='Тип позиции'),
        ),
        migrations.AlterField(
            model_name='techcarditem',
            name='material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tech_card_items_as_material', to='core.material', verbose_name='Материал'),
        ),
        migrations.AlterField(
            model_name='techcarditem',
            name='quantity',
            field=models.DecimalField(decimal_places=4, help_text='Норма расхода на одно изделие', max_digits=12, verbose_name='Количество на единицу'),
        ),
        migrations.AddConstraint(
            model_name='techcarditem',
            constraint=models.UniqueConstraint(condition=models.Q(('material__isnull', False)), fields=('tech_card', 'material'), name='core_techcarditem_tech_card_material_uniq'),
        ),
        migrations.AddConstraint(
            model_name='techcarditem',
            constraint=models.UniqueConstraint(condition=models.Q(('product__isnull', False)), fields=('tech_card', 'product'), name='core_techcarditem_tech_card_product_uniq'),
        ),
    ]
