# Generated by Django 6.0.3 on 2026-03-15 20:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_semifab_supply_products'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionDefect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=4, help_text='Не может превышать фактически выпущенное по этапу', max_digits=12, verbose_name='Объём брака')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('assignment_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='defects', to='core.productionassignmentitem', verbose_name='Позиция этапа')),
                ('product', models.ForeignKey(blank=True, help_text='По умолчанию — продукция техкарты этапа', null=True, on_delete=django.db.models.deletion.PROTECT, to='core.product', verbose_name='Изделие (брак)')),
            ],
            options={
                'verbose_name': 'Документ брака',
                'verbose_name_plural': 'Документы брака',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='productiondeviation',
            name='production_defect',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deviation', to='core.productiondefect', verbose_name='Документ брака'),
        ),
    ]
