# Generated by Django 6.0.3 on 2026-03-15 20:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_production_defect'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Группа товаров',
                'verbose_name_plural': 'Группы товаров',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name'], 'verbose_name': 'Товар (изделие)', 'verbose_name_plural': 'Товары и услуги'},
        ),
        migrations.AddField(
            model_name='product',
            name='article',
            field=models.CharField(blank=True, max_length=100, verbose_name='Артикул'),
        ),
        migrations.AddField(
            model_name='product',
            name='code',
            field=models.CharField(blank=True, max_length=100, verbose_name='Код'),
        ),
        migrations.AddField(
            model_name='product',
            name='country',
            field=models.CharField(blank=True, max_length=100, verbose_name='Страна происхождения'),
        ),
        migrations.AddField(
            model_name='product',
            name='external_code',
            field=models.CharField(blank=True, max_length=100, verbose_name='Внешний код'),
        ),
        migrations.AddField(
            model_name='product',
            name='min_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Ограничение: не продавать ниже этой цены', max_digits=12, null=True, verbose_name='Минимальная цена'),
        ),
        migrations.AddField(
            model_name='product',
            name='min_stock',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=12, null=True, verbose_name='Неснижаемый остаток'),
        ),
        migrations.AddField(
            model_name='product',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='product',
            name='purchase_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Подставляется в документы закупки; для дерева себестоимости', max_digits=12, null=True, verbose_name='Закупочная цена'),
        ),
        migrations.AddField(
            model_name='product',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplied_products', to='core.organization', verbose_name='Поставщик'),
        ),
        migrations.AddField(
            model_name='product',
            name='track_lots',
            field=models.BooleanField(default=False, help_text='Учёт товара по партиям и срокам годности', verbose_name='Учёт по партиям'),
        ),
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.CharField(default='шт', help_text='шт, м, м², кг и т.п.', max_length=50, verbose_name='Единица измерения'),
        ),
        migrations.AddField(
            model_name='product',
            name='volume',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True, verbose_name='Объём (м³)'),
        ),
        migrations.AddField(
            model_name='product',
            name='weight_kg',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='Вес (кг)'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='core.productgroup', verbose_name='Группа товаров'),
        ),
        migrations.CreateModel(
            name='ProductAnalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=1, verbose_name='Порядок')),
                ('analog_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='as_analog_of', to='core.product', verbose_name='Аналог')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analog_links', to='core.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Аналог товара',
                'verbose_name_plural': 'Аналоги товаров',
                'ordering': ['product', 'order'],
                'unique_together': {('product', 'analog_product')},
            },
        ),
    ]
