# Generated by Django 6.0.3 on 2026-03-15 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_product_card_extended'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='inn',
            field=models.CharField(blank=True, max_length=12, verbose_name='ИНН'),
        ),
        migrations.AddField(
            model_name='organization',
            name='is_individual',
            field=models.BooleanField(default=False, help_text='ИП (иначе — юридическое лицо)', verbose_name='Индивидуальный предприниматель'),
        ),
        migrations.AddField(
            model_name='organization',
            name='kpp',
            field=models.CharField(blank=True, help_text='Только для ЮЛ', max_length=9, verbose_name='КПП'),
        ),
        migrations.AddField(
            model_name='organization',
            name='legal_address',
            field=models.TextField(blank=True, verbose_name='Юридический адрес'),
        ),
        migrations.AddField(
            model_name='organization',
            name='ogrn',
            field=models.CharField(blank=True, max_length=15, verbose_name='ОГРН / ОГРНИП'),
        ),
    ]
