# Generated by Django 6.0.3 on 2026-03-15 21:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_organization_inn_fns'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductBarcode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode_type', models.CharField(choices=[('EAN13', 'EAN-13'), ('EAN8', 'EAN-8'), ('CODE128', 'Code 128'), ('OTHER', 'Другой')], default='EAN13', max_length=20, verbose_name='Тип штрихкода')),
                ('value', models.CharField(help_text='Введите вручную или отсканируйте. Один и тот же штрихкод не может быть у разных товаров.', max_length=64, unique=True, verbose_name='Штрихкод')),
                ('comment', models.CharField(blank=True, help_text='Например: основной, упаковка 6 шт, весовой.', max_length=255, verbose_name='Комментарий')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='barcodes', to='core.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Штрихкод товара',
                'verbose_name_plural': 'Штрихкоды товаров',
                'ordering': ['product', 'barcode_type', 'value'],
            },
        ),
    ]
