# Generated by Django 6.0.3 on 2026-03-16 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_product_barcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название прайс-листа')),
                ('base_price_type', models.CharField(choices=[('purchase', 'Закупочная цена'), ('planned', 'Плановая цена продажи'), ('min', 'Минимальная цена')], default='planned', max_length=20, verbose_name='Тип цен (база для расчёта)')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
            ],
            options={
                'verbose_name': 'Прайс-лист',
                'verbose_name_plural': 'Прайс-листы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PriceListColumn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название колонки')),
                ('order', models.PositiveSmallIntegerField(default=1, verbose_name='Порядок')),
                ('discount_markup_percent', models.DecimalField(blank=True, decimal_places=2, help_text='Положительное — наценка, отрицательное — скидка. Пусто — без изменения.', max_digits=6, null=True, verbose_name='Скидка (-) или наценка (+), %')),
                ('use_percent', models.BooleanField(default=True, help_text='Если снять — колонка без цен, заполняется вручную.', verbose_name='Скидка/наценка % от цены продажи')),
                ('price_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='columns', to='core.pricelist', verbose_name='Прайс-лист')),
            ],
            options={
                'verbose_name': 'Колонка прайс-листа',
                'verbose_name_plural': 'Колонки прайс-листа',
                'ordering': ['price_list', 'order', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='PriceListEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Цена')),
                ('column', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='core.pricelistcolumn', verbose_name='Колонка')),
                ('price_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='core.pricelist', verbose_name='Прайс-лист')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_list_entries', to='core.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Позиция прайс-листа',
                'verbose_name_plural': 'Позиции прайс-листа',
                'ordering': ['price_list', 'product__name', 'column__order'],
                'unique_together': {('price_list', 'product', 'column')},
            },
        ),
    ]
