# Generated by Django 6.0.3 on 2026-03-16 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_price_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_kind',
            field=models.CharField(choices=[('goods', 'Товар'), ('service', 'Услуга')], default='goods', help_text='Товар или услуга — для разделения в навигации и отчётах', max_length=20, verbose_name='Вид'),
        ),
    ]
