# Generated by Django 6.0.3 on 2026-03-16 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_product_kind'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('services', models.ManyToManyField(blank=True, help_text='Выберите услуги из справочника', limit_choices_to={'product_kind': 'service'}, related_name='service_groups', to='core.product', verbose_name='Услуги')),
            ],
            options={
                'verbose_name': 'Группа услуг',
                'verbose_name_plural': 'Группы услуг',
                'ordering': ['name'],
            },
        ),
    ]
