# Generated by Django 6.0.3 on 2026-03-16 19:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_service_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionstage',
            name='any_employee_can_execute',
            field=models.BooleanField(default=True, help_text='Если выключено, в производственном задании для этого этапа можно назначить только указанных исполнителей', verbose_name='Исполнителем может быть любой сотрудник'),
        ),
        migrations.AddField(
            model_name='productionstage',
            name='counterparty_executors',
            field=models.ManyToManyField(blank=True, help_text='Контрагенты (подрядчики), которые могут выполнять этап или услугу', related_name='stages_as_executor', to='core.organization', verbose_name='Исполнители (контрагенты)'),
        ),
        migrations.AddField(
            model_name='productionstage',
            name='executors',
            field=models.ManyToManyField(blank=True, help_text='Сотрудники, которые могут выполнять этот этап. Если «Любой сотрудник» выключен — только они видят задания по этапу.', related_name='stages_as_executor', to='core.employee', verbose_name='Исполнители (сотрудники)'),
        ),
        migrations.AddField(
            model_name='productionstage',
            name='hourly_rate',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Стоимость работы за 1 час для этого этапа', max_digits=10, null=True, verbose_name='Стоимость нормо-часа'),
        ),
        migrations.AddField(
            model_name='productionstage',
            name='master',
            field=models.ForeignKey(blank=True, help_text='Мастер может распределять задания между исполнителями', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stages_as_master', to='core.employee', verbose_name='Мастер этапа'),
        ),
        migrations.AddField(
            model_name='productionstage',
            name='material_warehouse',
            field=models.ForeignKey(blank=True, help_text='Склад, откуда брать материалы для выполнения этапа', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_stages', to='core.warehouse', verbose_name='Склад материалов'),
        ),
        migrations.AddField(
            model_name='productionstage',
            name='track_real_time',
            field=models.BooleanField(default=False, help_text='Фиксировать реальное время начала и завершения работы над этапом', verbose_name='Считать реальное время'),
        ),
    ]
