# Generated by Django 6.0.3 on 2026-03-22 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_production_stage_executors_warehouse'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organization',
            options={'ordering': ['name'], 'verbose_name': 'Контрагент', 'verbose_name_plural': 'Контрагенты'},
        ),
        migrations.AlterField(
            model_name='productionstage',
            name='any_employee_can_execute',
            field=models.BooleanField(default=True, help_text='Если выключено, в производственном задании для этого этапа можно назначить только указанных исполнителей', verbose_name='Любой сотрудник может выполнять этап'),
        ),
        migrations.AlterField(
            model_name='productionstage',
            name='track_real_time',
            field=models.BooleanField(default=False, help_text='Фиксировать фактическое время начала и окончания работы по этапу', verbose_name='Факт. время'),
        ),
    ]
