# Generated by Django 6.0.3 on 2026-03-22 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_shorten_track_real_time_verbose'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionStageCounterpartyService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_services', to='core.organization', verbose_name='Контрагент')),
                ('production_stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='counterparty_services', to='core.productionstage', verbose_name='Этап производства')),
                ('service', models.ForeignKey(blank=True, limit_choices_to={'product_kind': 'service'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stage_counterparty_services', to='core.product', verbose_name='Услуга')),
            ],
            options={
                'verbose_name': 'Услуга контрагента на этапе',
                'verbose_name_plural': 'Услуги контрагентов на этапе',
                'unique_together': {('production_stage', 'organization')},
            },
        ),
    ]
