# Generated by Django 6.0.3 on 2026-03-22 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_production_stage_counterparty_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='techcard',
            name='allocate_cost',
            field=models.BooleanField(blank=True, help_text='Не задано — по умолчанию как в учётной политике', null=True, verbose_name='Распределять себестоимость'),
        ),
        migrations.AddField(
            model_name='techcard',
            name='tech_process',
            field=models.ForeignKey(blank=True, help_text='После выбора техпроцесса доступны вкладки Продукция, Материалы и др.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tech_cards', to='core.techprocess', verbose_name='Техпроцесс'),
        ),
    ]
