# Generated by Django 6.0.3 on 2026-03-22 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_techcard_tech_process_allocate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='techcard',
            name='tech_process',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tech_cards', to='core.techprocess', verbose_name='Техпроцесс'),
        ),
    ]
