# Generated by Django 6.0.3 on 2026-03-28 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_techcarditem_production_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionassignment',
            name='name',
            field=models.CharField(blank=True, help_text='Краткое название документа, например: Пошив платья', max_length=255, verbose_name='Название задания'),
        ),
    ]
