# Generated by Django 6.0.3 on 2026-03-28 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_productionassignment_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionassignmentitem',
            name='quantity_planned',
            field=models.DecimalField(decimal_places=4, help_text='Сколько раз произвести продукцию по этой техкарте в рамках задания.', max_digits=12, verbose_name='Объём производства'),
        ),
        migrations.AlterField(
            model_name='productionassignmentitem',
            name='sequence',
            field=models.PositiveSmallIntegerField(default=1, help_text='Несколько техкарт выполняются по возрастанию этого номера (как в списке позиций). Изменение порядка здесь меняет порядок в веб-приложении (реестр этапов и т.п.).', verbose_name='Порядок выполнения'),
        ),
    ]
