# Generated by Django 6.0.3 on 2026-03-28 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_assignment_item_volume_help'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionassignment',
            name='reserve_materials',
            field=models.BooleanField(default=False, help_text='Зарезервировать материалы по потребности задания на выбранном складе материалов. При нескольких одновременных заданиях резерв помогает планировать снабжение.', verbose_name='Резерв материалов'),
        ),
        migrations.CreateModel(
            name='AssignmentMaterialReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='Количество')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_reservations', to='core.productionassignment', verbose_name='Производственное задание')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.material', verbose_name='Материал')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.warehouse', verbose_name='Склад')),
            ],
            options={
                'verbose_name': 'Резерв материала (задание)',
                'verbose_name_plural': 'Резервы материалов (задания)',
                'unique_together': {('assignment', 'material')},
            },
        ),
    ]
