# Generated by Django 6.0.3 on 2026-03-28 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_assignment_material_reserve'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionassignment',
            name='expectation',
            field=models.BooleanField(default=False, help_text='Если включено, выпуск по заданию ещё не готов: такую продукцию можно учитывать в отчётах «Остатки» и «Управление закупками» (плановые количества к производству). Помогает планировать продажи. Когда продукция произведена — снимите флажок.', verbose_name='Ожидание'),
        ),
    ]
