# Generated by Django 6.0.3 on 2026-03-28 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_productionassignment_expectation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at'], 'verbose_name': 'Заказ покупателя', 'verbose_name_plural': 'Заказы покупателей'},
        ),
    ]
