# Generated by Django 6.0.3 on 2026-03-28 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_orderitem_verbose_buyer'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='area_m2_manual',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='При ед. изм. м², кв. м — площадь одной единицы учёта', max_digits=14, null=True, verbose_name='Площадь (м²)'),
        ),
        migrations.AddField(
            model_name='product',
            name='length_m_manual',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='При ед. изм. м, п.м — протяжённость одной единицы (площадь не считается)', max_digits=12, null=True, verbose_name='Длина (м)'),
        ),
        migrations.AddField(
            model_name='product',
            name='sheet_area_cm2',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, help_text='Заполняется автоматически из габаритов (шт) или из м²', max_digits=16, null=True, verbose_name='Площадь листа (см²)'),
        ),
        migrations.AddField(
            model_name='product',
            name='sheet_area_m2',
            field=models.DecimalField(blank=True, decimal_places=6, editable=False, help_text='Заполняется автоматически; для отчётов и расчётов', max_digits=14, null=True, verbose_name='Площадь листа (м²)'),
        ),
        migrations.AddField(
            model_name='product',
            name='sheet_length_cm',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='При ед. изм. шт — сторона листа/заготовки, см', max_digits=12, null=True, verbose_name='Длина листа (см)'),
        ),
        migrations.AddField(
            model_name='product',
            name='sheet_width_cm',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='При ед. изм. шт — вторая сторона, см; площадь = длина × ширина', max_digits=12, null=True, verbose_name='Ширина листа (см)'),
        ),
    ]
