# Generated by Django 6.0.3 on 2026-03-28 19:03

from django.db import migrations, models
from django.db.models import F


def cm_to_mm(apps, schema_editor):
    from decimal import Decimal

    Product = apps.get_model("core", "Product")
    Product.objects.filter(sheet_length_cm__isnull=False).update(sheet_length_mm=F("sheet_length_cm") * 10)
    Product.objects.filter(sheet_width_cm__isnull=False).update(sheet_width_mm=F("sheet_width_cm") * 10)
    # Площади пересчитать из мм² (раньше считались как см×см)
    for p in Product.objects.exclude(sheet_length_mm=None).exclude(sheet_width_mm=None).iterator():
        L, W = p.sheet_length_mm, p.sheet_width_mm
        if L is not None and W is not None and L > 0 and W > 0:
            mm2 = (L * W).quantize(Decimal("0.001"))
            cm2 = (mm2 / Decimal("100")).quantize(Decimal("0.01"))
            m2 = (mm2 / Decimal("1000000")).quantize(Decimal("0.000001"))
            Product.objects.filter(pk=p.pk).update(sheet_area_cm2=cm2, sheet_area_m2=m2)


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0045_product_sheet_area_uom"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="sheet_length_mm",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                help_text="При ед. изм. шт — сторона листа/заготовки, мм",
                max_digits=12,
                null=True,
                verbose_name="Длина листа (мм)",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="sheet_width_mm",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                help_text="При ед. изм. шт — вторая сторона, мм; площадь = длина × ширина (мм²) → см² и м²",
                max_digits=12,
                null=True,
                verbose_name="Ширина листа (мм)",
            ),
        ),
        migrations.RunPython(cm_to_mm, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="product",
            name="sheet_length_cm",
        ),
        migrations.RemoveField(
            model_name="product",
            name="sheet_width_cm",
        ),
        migrations.AlterField(
            model_name="product",
            name="sheet_area_cm2",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                editable=False,
                help_text="Заполняется автоматически из габаритов в мм (шт) или из м²",
                max_digits=16,
                null=True,
                verbose_name="Площадь листа (см²)",
            ),
        ),
    ]
