# Generated by Django 6.0.3 on 2026-03-28 19:07

from django.db import migrations, models


def backfill_empty_articles(apps, schema_editor):
    Product = apps.get_model("core", "Product")
    for p in Product.objects.filter(article="").iterator():
        Product.objects.filter(pk=p.pk).update(article=f"ART-{p.pk:06d}")


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_product_sheet_mm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='article',
            field=models.CharField(blank=True, help_text='Если оставить пустым, при сохранении присвоится автоматически (ART-000123).', max_length=100, verbose_name='Артикул'),
        ),
        migrations.RunPython(backfill_empty_articles, migrations.RunPython.noop),
    ]
