# Generated by Django 6.0.3 on 2026-03-28 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_product_article_auto_help'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sheet_area_mm2',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, help_text='Авто: ед. шт — Д×Ш; ед. м² — из м²', max_digits=18, null=True, verbose_name='Площадь (мм²)'),
        ),
        migrations.AddField(
            model_name='product',
            name='sheet_thickness_mm',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Для объёма: ед. шт — толщина листа; ед. м² — высота/толщина слоя; ед. п.м — сечение с шириной', max_digits=12, null=True, verbose_name='Толщина (мм)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='length_m_manual',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Ед. п.м — длина единицы, м; объём = длина × ширина × толщина (мм→м³)', max_digits=12, null=True, verbose_name='Длина (м)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sheet_area_cm2',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, help_text='Авто из мм² или из м²', max_digits=16, null=True, verbose_name='Площадь (см²)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sheet_area_m2',
            field=models.DecimalField(blank=True, decimal_places=6, editable=False, help_text='Авто; для отчётов и расчётов', max_digits=14, null=True, verbose_name='Площадь (м²)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sheet_length_mm',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Ед. шт — длина листа/заготовки; ед. п.м — не используется для длины (см. «Длина (м)»)', max_digits=12, null=True, verbose_name='Длина (мм)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sheet_width_mm',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Ед. шт — ширина листа; ед. п.м — размер сечения', max_digits=12, null=True, verbose_name='Ширина (мм)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='volume',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Для ед. шт: считается из Д×Ш×Т (мм). Для м²: из площади×толщина. Для п.м: из длины (м)×Ш×Т (мм) как профиль.', max_digits=12, null=True, verbose_name='Объём (м³)'),
        ),
    ]
