# Generated by Django 6.0.3 on 2026-03-28 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_product_sheet_thickness_geometry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sheet_area_m2',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, help_text='Авто, м² с точностью до 2 знаков после запятой', max_digits=14, null=True, verbose_name='Площадь (м²)'),
        ),
    ]
