# Generated by Django 6.0.3 on 2026-03-28 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_product_sheet_area_m2_2dp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='area_m2_manual',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Заполняйте, если ед. изм. м² / кв. м — площадь одной единицы учёта (ввод вручную)', max_digits=14, null=True, verbose_name='Площадь учёта (м²)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sheet_area_m2',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, help_text='Считается автоматически из габаритов (шт) или из площади учёта (м²); 2 знака после запятой', max_digits=14, null=True, verbose_name='Площадь расчётная (м²)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sheet_area_mm2',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, help_text='Авто: ед. шт — Д×Ш; ед. м² — из площади учёта', max_digits=18, null=True, verbose_name='Площадь (мм²)'),
        ),
    ]
