# Generated by Django 6.0.3 on 2026-03-28 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_product_area_labels_distinct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sheet_area_cm2',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, help_text='Авто из мм² или из площади учёта (м²)', max_digits=16, null=True, verbose_name='Площадь (см²)'),
        ),
    ]
