# Generated by Django 6.0.3 on 2026-03-28 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0051_product_sheet_area_cm2_help'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='length_m_manual',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Ед. шт — считается из «Длина (мм)» ÷ 1000 (авто). Ед. п.м / м — ввод вручную; объём = длина × ширина × толщина сечения (мм→м³).', max_digits=12, null=True, verbose_name='Длина (м)'),
        ),
    ]
