# Generated by Django 6.0.3 on 2026-03-28 20:24

from decimal import ROUND_HALF_UP, Decimal

from django.db import migrations, models


def round_product_min_stock(apps, schema_editor):
    Product = apps.get_model("core", "Product")
    for pk, raw in Product.objects.values_list("pk", "min_stock"):
        if raw is None:
            continue
        rounded = raw.quantize(Decimal("1"), rounding=ROUND_HALF_UP)
        if raw != rounded:
            Product.objects.filter(pk=pk).update(min_stock=rounded)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_product_length_m_auto_from_mm'),
    ]

    operations = [
        migrations.RunPython(round_product_min_stock, noop_reverse),
        migrations.AlterField(
            model_name='product',
            name='min_stock',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, help_text='Целое число единиц учёта (дробная часть при сохранении округляется)', max_digits=12, null=True, verbose_name='Неснижаемый остаток'),
        ),
    ]
