# Generated by Django 6.0.3 on 2026-03-28 20:28

from django.db import migrations, models


def copy_sheet_area_m2_to_area_manual(apps, schema_editor):
    Product = apps.get_model("core", "Product")
    qs = Product.objects.filter(area_m2_manual__isnull=True).exclude(sheet_area_m2__isnull=True)
    for p in qs.iterator(chunk_size=500):
        Product.objects.filter(pk=p.pk).update(area_m2_manual=p.sheet_area_m2)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_product_min_stock_integer'),
    ]

    operations = [
        migrations.RunPython(copy_sheet_area_m2_to_area_manual, noop_reverse),
        migrations.RemoveField(
            model_name='product',
            name='sheet_area_m2',
        ),
        migrations.AlterField(
            model_name='product',
            name='area_m2_manual',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Ед. м² / кв. м — ввод вручную. Ед. шт — считается из длины × ширины (мм), только просмотр.', max_digits=14, null=True, verbose_name='Площадь (м²)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sheet_area_cm2',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, help_text='Авто из мм² или из площади (м²)', max_digits=16, null=True, verbose_name='Площадь (см²)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sheet_area_mm2',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, help_text='Авто: ед. шт — Д×Ш; ед. м² — из площади (м²)', max_digits=18, null=True, verbose_name='Площадь (мм²)'),
        ),
    ]
