# Generated by Django 6.0.3 on 2026-03-28 20:44

from decimal import ROUND_HALF_UP, Decimal

from django.db import migrations, models


def round_sheet_mm(apps, schema_editor):
    Product = apps.get_model("core", "Product")
    q0 = Decimal("1")
    for p in Product.objects.iterator(chunk_size=500):
        updates = {}
        for name in ("sheet_length_mm", "sheet_width_mm", "sheet_thickness_mm"):
            v = getattr(p, name)
            if v is not None:
                r = v.quantize(q0, rounding=ROUND_HALF_UP)
                if r != v:
                    updates[name] = r
        if updates:
            Product.objects.filter(pk=p.pk).update(**updates)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0054_remove_product_sheet_area_m2'),
    ]

    operations = [
        migrations.RunPython(round_sheet_mm, noop_reverse),
        migrations.AlterField(
            model_name='product',
            name='sheet_length_mm',
            field=models.DecimalField(blank=True, decimal_places=0, help_text='Целые мм. Ед. шт — длина листа/заготовки; ед. п.м — не для длины (см. «Длина (м)»)', max_digits=12, null=True, verbose_name='Длина (мм)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sheet_thickness_mm',
            field=models.DecimalField(blank=True, decimal_places=0, help_text='Целые мм. Ед. шт — толщина листа; ед. м² — слой; ед. п.м — сечение с шириной', max_digits=12, null=True, verbose_name='Толщина (мм)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sheet_width_mm',
            field=models.DecimalField(blank=True, decimal_places=0, help_text='Целые мм. Ед. шт — ширина листа; ед. п.м — размер сечения', max_digits=12, null=True, verbose_name='Ширина (мм)'),
        ),
    ]
