# Generated by Django 6.0.3 on 2026-03-28 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0055_product_sheet_mm_integer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='area_m2_manual',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Ед. м² / кв. м — ввод вручную. Ед. шт — считается из длины × ширины (мм), только просмотр.', max_digits=14, null=True, verbose_name='Площадь в м²'),
        ),
        migrations.AlterField(
            model_name='product',
            name='length_m_manual',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Ед. шт — из «Длина в мм» ÷ 1000 (авто). Ед. п.м / м — вручную; объём = длина × ширина × толщина сечения (мм→м³).', max_digits=12, null=True, verbose_name='Длина в м'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sheet_area_cm2',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, help_text='Авто из мм² или из площади (м²)', max_digits=16, null=True, verbose_name='Площадь в см²'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sheet_area_mm2',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, help_text='Авто: ед. шт — Д×Ш; ед. м² — из площади (м²)', max_digits=18, null=True, verbose_name='Площадь в мм²'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sheet_length_mm',
            field=models.DecimalField(blank=True, decimal_places=0, help_text='Целые мм. Ед. шт — длина листа/заготовки; ед. п.м — не для длины (см. «Длина в м»)', max_digits=12, null=True, verbose_name='Длина в мм'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sheet_thickness_mm',
            field=models.DecimalField(blank=True, decimal_places=0, help_text='Целые мм. Ед. шт — толщина листа; ед. м² — слой; ед. п.м — сечение с шириной', max_digits=12, null=True, verbose_name='Толщина в мм'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sheet_width_mm',
            field=models.DecimalField(blank=True, decimal_places=0, help_text='Целые мм. Ед. шт — ширина листа; ед. п.м — размер сечения', max_digits=12, null=True, verbose_name='Ширина в мм'),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(default='шт', help_text='шт, м, м², кг и т.п.', max_length=50, verbose_name='Ед. изм.'),
        ),
        migrations.AlterField(
            model_name='product',
            name='volume',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='м³. Для ед. шт: из Д×Ш×Т (мм). Для м²: из площади×толщина. Для п.м: из длины (м)×Ш×Т (мм).', max_digits=12, null=True, verbose_name='Объём'),
        ),
        migrations.AlterField(
            model_name='product',
            name='weight_kg',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Килограммы', max_digits=12, null=True, verbose_name='Вес'),
        ),
    ]
