# Generated by Django 6.0.3 on 2026-03-28 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0056_product_uom_field_labels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='area_m2_manual',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Ед. м² / кв. м — ввод вручную. Ед. шт — считается из длины × ширины (мм), только просмотр.', max_digits=14, null=True, verbose_name='Пл. в м²'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sheet_area_cm2',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, help_text='Авто из мм² или из пл. (м²)', max_digits=16, null=True, verbose_name='Пл. в см²'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sheet_area_mm2',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, help_text='Авто: ед. шт — Д×Ш; ед. м² — из пл. (м²)', max_digits=18, null=True, verbose_name='Пл. в мм²'),
        ),
        migrations.AlterField(
            model_name='product',
            name='volume',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='м³. Для ед. шт: из Д×Ш×Т (мм). Для м²: из пл.×толщина. Для п.м: из длины (м)×Ш×Т (мм).', max_digits=12, null=True, verbose_name='Объём'),
        ),
    ]
