# Generated by Django 6.0.3 on 2026-03-29 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0057_product_area_pl_abbrev'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(default='шт', help_text='В карточке — список частых значений; можно ввести любую ед. изм. (шт, м, м², кг и т.п.).', max_length=50, verbose_name='Ед. изм.'),
        ),
    ]
