# Generated by Django 6.0.3 on 2026-03-29 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0058_product_unit_help_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='volume',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Значение в м³. Для ед. шт: из Д×Ш×Т (мм). Для м²: из пл.×толщина. Для п.м: из длины (м)×Ш×Т (мм).', max_digits=12, null=True, verbose_name='Объём м³'),
        ),
    ]
