# Generated by Django 6.0.3 on 2026-03-29 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0059_product_volume_label_m3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(blank=True, help_text='Для товара при группе и длине/ширине в мм пересобирается при каждом сохранении; при толщине она включается в наименование. Иначе введите наименование вручную.', max_length=255, verbose_name='Наименование'),
        ),
    ]
