# Generated by Django 6.0.3 on 2026-03-29 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0061_operationtype_result_adjective_goods_naming'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='planned_markup_percent',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Вкладка «Стоимость»: плановая по формуле закупочная × (1 + %/100). Поля на вкладке «Цены» подставляются только по кнопкам.', max_digits=6, null=True, verbose_name='Наценка к плановой цене, %'),
        ),
    ]
