# Generated by Django 6.0.3 on 2026-03-29 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0062_product_planned_markup_percent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_kind',
            field=models.CharField(choices=[('goods', 'Товар'), ('service', 'Услуга'), ('material', 'Материал')], default='goods', help_text='Товар, услуга или материал — для разделения в навигации и отчётах', max_length=20, verbose_name='Вид'),
        ),
    ]
