# Generated by Django 6.0.3 on 2026-03-29 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0063_product_kind_material_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionstage',
            name='cut_rate_per_meter',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Для этапов вроде лазерной резки: затраты на 1 погонный метр реза. В техкарте на строке с этим этапом укажите норму длины реза на 1 изделие (м). Себестоимость строки: метры × эта ставка. Пусто — считать только по нормо-часу (если используете).', max_digits=12, null=True, verbose_name='Стоимость метра реза, ₽'),
        ),
        migrations.AddField(
            model_name='techcarditem',
            name='cut_length_meters_per_unit',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Погонные метры реза на одно изделие (лазер и т.п.). Учитывается, если у выбранного этапа задана «Стоимость метра реза».', max_digits=12, null=True, verbose_name='Норма длины реза на 1 изд., м'),
        ),
        migrations.AlterField(
            model_name='productionstage',
            name='hourly_rate',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='₽ за час работы этапа (станок или участок). Для лазера можно дополнительно задать стоимость метра реза ниже.', max_digits=10, null=True, verbose_name='Стоимость нормо-часа'),
        ),
    ]
