# Generated by Django 6.0.3 on 2026-03-29 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0065_seed_sanding_tech_processes'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='techcarditem',
            name='core_techcarditem_tech_card_material_uniq',
        ),
        migrations.AlterField(
            model_name='techcard',
            name='product',
            field=models.ForeignKey(blank=True, help_text='Изделие, для которого составлена карта (необязательно). При сохранении техкарты нормы позиций «материал» копируются в карточку изделия для расчёта себестоимости. Если техкарт несколько, в карточке товара остаются нормы из последней сохранённой карты с этим изделием.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tech_cards', to='core.product', verbose_name='Изделие'),
        ),
    ]
