# Generated by Django 6.0.3 on 2026-03-29 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0066_remove_techcarditem_material_uniq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='techcarditem',
            name='quantity',
            field=models.DecimalField(decimal_places=4, help_text='Норма расхода на одно изделие. Один и тот же материал в нескольких строках (разные этапы) суммируется при резерве и списании. Один физический лист на два этапа: одна строка с количеством 1, на втором этапе лист не дублируйте (или 0); расходники (диск) — отдельными строками по этапам.', max_digits=12, verbose_name='Количество на единицу'),
        ),
    ]
