# Generated by Django 6.0.3 on 2026-03-29 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0067_techcarditem_quantity_help_conduct_agg'),
    ]

    operations = [
        migrations.AddField(
            model_name='techcard',
            name='labor_norm_hour_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Руб. за 1 нормо-час по этой техкарте.', max_digits=12, null=True, verbose_name='Стоимость нормо-часа'),
        ),
        migrations.AddField(
            model_name='techcard',
            name='labor_norm_hours',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Норма времени на 1 шт. готовой продукции (нормо-часы).', max_digits=12, null=True, verbose_name='Нормо-часы'),
        ),
        migrations.AddField(
            model_name='techcard',
            name='production_overhead_per_unit',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Прочие затраты на 1 шт. (энергия, амортизация и т.п.), без оплаты труда по норме, ₽.', max_digits=12, verbose_name='Затраты на производство'),
        ),
    ]
