# Generated by Django 6.0.3 on 2026-03-29 13:45

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


def migrate_labor_norms_to_lines(apps, schema_editor):
    TechCard = apps.get_model("core", "TechCard")
    TechCardLaborLine = apps.get_model("core", "TechCardLaborLine")
    TechProcessStage = apps.get_model("core", "TechProcessStage")
    for tc in TechCard.objects.all():
        nh = getattr(tc, "labor_norm_hours", None)
        if nh is None:
            continue
        first = (
            TechProcessStage.objects.filter(tech_process_id=tc.tech_process_id)
            .order_by("order")
            .first()
        )
        if not first:
            continue
        overhead = getattr(tc, "production_overhead_per_unit", None) or Decimal("0")
        TechCardLaborLine.objects.get_or_create(
            tech_card_id=tc.pk,
            production_stage_id=first.production_stage_id,
            defaults={
                "norm_hours": nh,
                "overhead_per_unit": overhead,
            },
        )


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0068_techcard_labor_norms_money"),
    ]

    operations = [
        migrations.CreateModel(
            name="TechCardLaborLine",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "norm_hours",
                    models.DecimalField(
                        decimal_places=4,
                        default=0,
                        help_text="Норма на 1 шт. по этому этапу, нормо-часы.",
                        max_digits=12,
                        verbose_name="Нормо-часы",
                    ),
                ),
                (
                    "overhead_per_unit",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0,
                        help_text="Прочие затраты на 1 шт. по этапу, ₽.",
                        max_digits=12,
                        verbose_name="Затраты на производство",
                    ),
                ),
                (
                    "production_stage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tech_card_labor_lines",
                        to="core.productionstage",
                        verbose_name="Этап",
                    ),
                ),
                (
                    "tech_card",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="labor_lines",
                        to="core.techcard",
                        verbose_name="Технологическая карта",
                    ),
                ),
            ],
            options={
                "verbose_name": "Норма времени по этапу (деньги)",
                "verbose_name_plural": "Нормы времени и деньги по этапам",
                "unique_together": {("tech_card", "production_stage")},
            },
        ),
        migrations.RunPython(migrate_labor_norms_to_lines, noop_reverse),
        migrations.RemoveField(
            model_name="techcard",
            name="labor_norm_hour_rate",
        ),
        migrations.RemoveField(
            model_name="techcard",
            name="labor_norm_hours",
        ),
        migrations.RemoveField(
            model_name="techcard",
            name="production_overhead_per_unit",
        ),
    ]
