# Generated by Django 6.0.3 on 2026-03-29 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0069_techcard_labor_lines_from_stage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='techcardlaborline',
            name='production_stage',
            field=models.ForeignKey(help_text='Стоимость нормо-часа подставляется из справочника этапа.', on_delete=django.db.models.deletion.PROTECT, related_name='tech_card_labor_lines', to='core.productionstage', verbose_name='Этап'),
        ),
    ]
