# Generated by Django 6.0.3 on 2026-03-29 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0070_alter_techcardlaborline_stage_help'),
    ]

    operations = [
        migrations.AddField(
            model_name='techcard',
            name='labor_norm_input_unit',
            field=models.CharField(choices=[('hours', 'Нормо-часы'), ('minutes', 'Минуты')], default='hours', help_text='В разделе «Деньги»: вводить норму по этапам в часах или в минутах. В расчётах всегда используются нормо-часы.', max_length=16, verbose_name='Ввод нормы времени'),
        ),
    ]
