# Generated by Django 6.0.3 on 2026-04-05 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0071_techcard_labor_norm_input_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='techcarditem',
            name='component_tech_card',
            field=models.ForeignKey(blank=True, help_text='Техкарта изготовления полуфабриката (для позиций с типом «Комплектующие»).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referenced_by_component_items', to='core.techcard', verbose_name='Техкарта полуфабриката'),
        ),
    ]
