# Generated by Django 6.0.3 on 2026-04-07 19:38

import django.db.models.deletion
from django.db import migrations, models


def copy_product_photo_to_gallery(apps, schema_editor):
    Product = apps.get_model("core", "Product")
    ProductGalleryImage = apps.get_model("core", "ProductGalleryImage")
    for p in Product.objects.all():
        if not p.photo:
            continue
        if ProductGalleryImage.objects.filter(product_id=p.pk).exists():
            continue
        ProductGalleryImage.objects.create(product=p, image=p.photo, sort_order=0)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0076_product_vat_rate_percent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='techcarditem',
            options={'ordering': ['item_kind', 'composition_order', 'pk'], 'verbose_name': 'Позиция технологической карты', 'verbose_name_plural': 'Позиции технологической карты'},
        ),
        migrations.CreateModel(
            name='ProductGalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/gallery/', verbose_name='Файл')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='core.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Изображение товара',
                'verbose_name_plural': 'Изображения товара',
                'ordering': ['product', 'sort_order', 'pk'],
            },
        ),
        migrations.RunPython(copy_product_photo_to_gallery, noop_reverse),
    ]
