# Generated by Django 6.0.3 on 2026-04-07 20:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0078_product_supplier_help_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='supplier',
            field=models.ForeignKey(blank=True, help_text='Контрагент из справочника; при закупках используется как основной поставщик по этой номенклатуре.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplied_products', to='core.organization', verbose_name='Контрагент'),
        ),
    ]
