# Generated by Django 6.0.3 on 2026-04-07 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0079_alter_product_supplier_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='is_buyer',
            field=models.BooleanField(default=True, help_text='Роль в продажах: клиент по заказам покупателей (при появлении привязки к контрагенту).', verbose_name='Покупатель'),
        ),
        migrations.AddField(
            model_name='organization',
            name='is_supplier',
            field=models.BooleanField(default=True, help_text='Роль в закупках: поставщик номенклатуры, приёмки, счетов от поставщика.', verbose_name='Поставщик'),
        ),
    ]
