# Generated by Django 6.0.3 on 2026-04-07 21:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0080_organization_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='supplier',
            field=models.ForeignKey(blank=True, help_text='Организация из справочника контрагентов — основной поставщик по закупкам для этой номенклатуры.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplied_products', to='core.organization', verbose_name='Поставщик'),
        ),
    ]
