# Generated by Django 6.0.3 on 2026-05-10 20:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0081_product_supplier_verbose_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=255, verbose_name='Клиент')),
                ('phone', models.CharField(max_length=64, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('request_title', models.CharField(max_length=255, verbose_name='Наименование заказа')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Количество')),
                ('deadline', models.DateField(blank=True, null=True, verbose_name='Желаемый срок')),
                ('specs', models.TextField(blank=True, verbose_name='Параметры и требования')),
                ('material_preferences', models.CharField(blank=True, max_length=255, verbose_name='Предпочтения по материалу')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий клиента')),
                ('manager_comment', models.TextField(blank=True, verbose_name='Комментарий менеджера')),
                ('status', models.CharField(choices=[('new', 'Новая'), ('in_review', 'В обработке'), ('quoted', 'Оценена'), ('approved', 'Согласована'), ('rejected', 'Отклонена'), ('converted', 'Конвертирована в заказ')], default='new', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_requests', to='core.product', verbose_name='Товар/основа')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_requests', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Запрос на производство',
                'verbose_name_plural': 'Запросы на производство',
                'ordering': ['-created_at'],
            },
        ),
    ]
