# Generated by Django 6.0.3 on 2026-05-10 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0082_production_request_mvp'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionrequest',
            name='layout_file',
            field=models.FileField(blank=True, null=True, upload_to='production_requests/layouts/', verbose_name='Файл макета'),
        ),
    ]
