# Generated by Django 6.0.3 on 2026-05-10 21:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0084_emailverification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionRequestMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Сообщение')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_request_messages', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('production_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='core.productionrequest', verbose_name='Запрос на производство')),
            ],
            options={
                'verbose_name': 'Сообщение по запросу на производство',
                'verbose_name_plural': 'Сообщения по запросам на производство',
                'ordering': ['created_at'],
            },
        ),
    ]
