# Generated by Django 6.0.3 on 2026-05-10 21:35

from django.db import migrations, models


def backfill_is_employee_message(apps, schema_editor):
    Message = apps.get_model("core", "ProductionRequestMessage")
    for msg in Message.objects.select_related("production_request").all():
        req_user_id = getattr(msg.production_request, "user_id", None)
        msg.is_employee_message = bool(msg.author_id and msg.author_id != req_user_id)
        msg.save(update_fields=["is_employee_message"])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0085_productionrequestmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionrequestmessage',
            name='is_employee_message',
            field=models.BooleanField(default=False, verbose_name='Сообщение сотрудника'),
        ),
        migrations.RunPython(backfill_is_employee_message, migrations.RunPython.noop),
    ]
