# Generated by Django 6.0.3 on 2026-05-11 18:50

from django.db import migrations, models


def backfill_scan_status(apps, schema_editor):
    ProductionRequest = apps.get_model("core", "ProductionRequest")
    ProductionRequest.objects.filter(layout_file__isnull=True).update(
        layout_scan_status="skipped",
        layout_scan_result="Файл не был приложен.",
    )
    ProductionRequest.objects.filter(layout_file="").update(
        layout_scan_status="skipped",
        layout_scan_result="Файл не был приложен.",
    )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0086_productionrequestmessage_is_employee_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionrequest',
            name='layout_is_quarantined',
            field=models.BooleanField(default=False, verbose_name='Файл в карантине'),
        ),
        migrations.AddField(
            model_name='productionrequest',
            name='layout_quarantine_path',
            field=models.CharField(blank=True, max_length=512, verbose_name='Путь в карантине'),
        ),
        migrations.AddField(
            model_name='productionrequest',
            name='layout_scan_result',
            field=models.TextField(blank=True, verbose_name='Результат проверки файла'),
        ),
        migrations.AddField(
            model_name='productionrequest',
            name='layout_scan_status',
            field=models.CharField(choices=[('pending', 'Ожидает проверки'), ('clean', 'Проверен, угроз не найдено'), ('infected', 'Заблокирован: найдена угроза'), ('failed', 'Ошибка проверки'), ('skipped', 'Проверка не выполнена')], default='pending', max_length=20, verbose_name='Статус проверки файла'),
        ),
        migrations.AddField(
            model_name='productionrequest',
            name='layout_scanned_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Проверено в'),
        ),
        migrations.RunPython(backfill_scan_status, migrations.RunPython.noop),
    ]
