# Generated by Django 6.0.3 on 2026-05-11 19:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0087_productionrequest_layout_is_quarantined_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='bank_account',
            field=models.CharField(blank=True, max_length=64, verbose_name='Расчётный счёт'),
        ),
        migrations.AddField(
            model_name='organization',
            name='bank_bik',
            field=models.CharField(blank=True, max_length=20, verbose_name='БИК'),
        ),
        migrations.AddField(
            model_name='organization',
            name='bank_corr_account',
            field=models.CharField(blank=True, max_length=64, verbose_name='Корреспондентский счёт'),
        ),
        migrations.AddField(
            model_name='organization',
            name='bank_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Банк'),
        ),
        migrations.AddField(
            model_name='organization',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='organization',
            name='phone',
            field=models.CharField(blank=True, max_length=64, verbose_name='Телефон'),
        ),
        migrations.AddField(
            model_name='organization',
            name='signer_authority',
            field=models.CharField(blank=True, help_text='Например: Устав, доверенность №... от ...', max_length=255, verbose_name='Основание полномочий'),
        ),
        migrations.AddField(
            model_name='organization',
            name='signer_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Подписант (ФИО)'),
        ),
        migrations.AddField(
            model_name='organization',
            name='signer_position',
            field=models.CharField(blank=True, max_length=255, verbose_name='Должность подписанта'),
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=64, verbose_name='Номер договора')),
                ('contract_date', models.DateField(verbose_name='Дата договора')),
                ('valid_until', models.DateField(blank=True, null=True, verbose_name='Действует до')),
                ('contract_type', models.CharField(choices=[('supplier', 'Договор с поставщиком'), ('customer', 'Договор с клиентом')], max_length=20, verbose_name='Тип договора')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('active', 'Действует'), ('expired', 'Истёк'), ('cancelled', 'Расторгнут')], default='draft', max_length=20, verbose_name='Статус')),
                ('payment_terms', models.TextField(blank=True, verbose_name='Условия оплаты')),
                ('delivery_terms', models.TextField(blank=True, verbose_name='Условия поставки/оказания')),
                ('subject', models.TextField(blank=True, verbose_name='Предмет договора')),
                ('amount_limit', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Лимит суммы')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('counterparty', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contracts_as_counterparty', to='core.organization', verbose_name='Контрагент')),
                ('our_organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contracts_as_our_side', to='core.organization', verbose_name='Наша организация')),
            ],
            options={
                'verbose_name': 'Договор',
                'verbose_name_plural': 'Договоры',
                'ordering': ['-contract_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ContractVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.PositiveIntegerField(default=1, verbose_name='Версия')),
                ('generated_text', models.TextField(blank=True, verbose_name='Текст версии')),
                ('generated_file', models.FileField(blank=True, upload_to='contracts/generated/', verbose_name='Файл версии')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='core.contract', verbose_name='Договор')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contract_versions', to=settings.AUTH_USER_MODEL, verbose_name='Кем создано')),
            ],
            options={
                'verbose_name': 'Версия договора',
                'verbose_name_plural': 'Версии договоров',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddConstraint(
            model_name='contract',
            constraint=models.UniqueConstraint(fields=('number', 'our_organization', 'counterparty'), name='uniq_contract_number_per_pair'),
        ),
        migrations.AddConstraint(
            model_name='contractversion',
            constraint=models.UniqueConstraint(fields=('contract', 'version_number'), name='uniq_contract_version_number'),
        ),
    ]
