# Generated by Django 6.0.3 on 2026-05-13 18:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0088_organization_bank_account_organization_bank_bik_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=32, unique=True, verbose_name='Номер счёта')),
                ('customer_name', models.CharField(max_length=255, verbose_name='Клиент')),
                ('customer_email', models.EmailField(blank=True, max_length=254, verbose_name='Email клиента')),
                ('customer_phone', models.CharField(blank=True, max_length=64, verbose_name='Телефон клиента')),
                ('issue_date', models.DateField(auto_now_add=True, verbose_name='Дата счёта')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Оплатить до')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Сумма')),
                ('purpose', models.TextField(blank=True, verbose_name='Назначение платежа')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('sent', 'Отправлен клиенту'), ('paid', 'Оплачен'), ('cancelled', 'Отменён')], default='draft', max_length=20, verbose_name='Статус')),
                ('sent_to_chat_at', models.DateTimeField(blank=True, null=True, verbose_name='Отправлен клиенту в чат')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_customer_invoices', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_invoices', to='core.order', verbose_name='Заказ покупателя')),
                ('our_organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_customer_invoices', to='core.organization', verbose_name='Наша организация')),
                ('production_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_invoices', to='core.productionrequest', verbose_name='Запрос на производство')),
            ],
            options={
                'verbose_name': 'Счёт клиенту',
                'verbose_name_plural': 'Счета клиентам',
                'ordering': ['-created_at', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='BankPaymentOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=32, unique=True, verbose_name='Номер платежного поручения')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Сумма')),
                ('payment_date', models.DateField(auto_now_add=True, verbose_name='Дата платежа')),
                ('recipient_name', models.CharField(max_length=255, verbose_name='Получатель')),
                ('recipient_inn', models.CharField(blank=True, max_length=12, verbose_name='ИНН получателя')),
                ('recipient_account', models.CharField(blank=True, max_length=64, verbose_name='Счёт получателя')),
                ('recipient_bank_name', models.CharField(blank=True, max_length=255, verbose_name='Банк получателя')),
                ('recipient_bank_bik', models.CharField(blank=True, max_length=20, verbose_name='БИК банка')),
                ('recipient_bank_corr_account', models.CharField(blank=True, max_length=64, verbose_name='Корр. счёт банка')),
                ('purpose', models.TextField(blank=True, verbose_name='Назначение платежа')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('sent', 'Отправлено в банк'), ('accepted', 'Принято банком'), ('failed', 'Ошибка отправки'), ('not_configured', 'Интеграция не настроена')], default='draft', max_length=20, verbose_name='Статус')),
                ('external_operation_id', models.CharField(blank=True, max_length=128, verbose_name='ID операции в банке')),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='Отправленный payload')),
                ('bank_response', models.TextField(blank=True, verbose_name='Ответ банка')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Отправлено в банк')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_bank_payment_orders', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('customer_invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_payment_orders', to='core.customerinvoice', verbose_name='Счёт клиенту')),
            ],
            options={
                'verbose_name': 'Платёжное поручение',
                'verbose_name_plural': 'Платёжные поручения',
                'ordering': ['-created_at', '-pk'],
            },
        ),
    ]
