# Generated by Django 6.0.3 on 2026-05-13 19:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0089_customerinvoice_bankpaymentorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerinvoice',
            name='issue_date',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='Дата счёта'),
        ),
    ]
