# Generated by Django 6.0.3 on 2026-05-13 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0090_alter_customerinvoice_issue_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='fns_raw_data',
            field=models.JSONField(blank=True, default=dict, verbose_name='Данные ФНС (raw)'),
        ),
        migrations.AddField(
            model_name='organization',
            name='fns_status',
            field=models.CharField(blank=True, max_length=255, verbose_name='Статус по ФНС'),
        ),
        migrations.AddField(
            model_name='organization',
            name='fns_updated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Обновлено из ФНС'),
        ),
    ]
