# Generated by Django 6.0.3 on 2026-05-13 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0091_organization_fns_raw_data_organization_fns_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='general_director',
            field=models.CharField(blank=True, max_length=255, verbose_name='Генеральный директор'),
        ),
    ]
