# Generated by Django 6.0.3 on 2026-05-24 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0092_organization_general_director'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseLedgerEntry',
            fields=[
            ],
            options={
                'verbose_name': 'Расход',
                'verbose_name_plural': 'Расходы',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.organization',),
        ),
    ]
