# Generated by Django 6.0.3 on 2026-06-21 19:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0093_expenseledgerentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionassignment',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_assignments', to='core.order', verbose_name='Заказ покупателя'),
        ),
        migrations.AddField(
            model_name='productionassignment',
            name='order_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_assignments', to='core.orderitem', verbose_name='Позиция заказа покупателя'),
        ),
    ]
