# Generated by Django 6.0.3 on 2026-06-21 20:30

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0094_productionassignment_order_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductModification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Например: «С гравировкой», «Большая 300x180 мм».', max_length=255, verbose_name='Название модификации')),
                ('article', models.CharField(blank=True, max_length=64, verbose_name='Артикул модификации')),
                ('code', models.CharField(blank=True, max_length=64, verbose_name='Код модификации')),
                ('quantity_factor', models.DecimalField(decimal_places=3, default=Decimal('1'), help_text='1.000 — как у базового изделия; 1.200 — расход/себестоимость выше на 20%.', max_digits=8, verbose_name='Коэффициент расхода')),
                ('planned_price', models.DecimalField(blank=True, decimal_places=2, help_text='Если заполнено — используется как цена продажи этой модификации.', max_digits=12, null=True, verbose_name='Цена продажи (если фикс.)')),
                ('planned_markup_percent', models.DecimalField(blank=True, decimal_places=2, help_text='Если «Цена продажи» пустая: себестоимость × (1 + %/100), затем округление.', max_digits=6, null=True, verbose_name='Наценка, %')),
                ('sort_order', models.PositiveSmallIntegerField(default=1, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('comment', models.CharField(blank=True, max_length=255, verbose_name='Комментарий')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modifications', to='core.product', verbose_name='Базовое изделие')),
            ],
            options={
                'verbose_name': 'Модификация товара',
                'verbose_name_plural': 'Модификации товаров',
                'ordering': ['product', 'sort_order', 'name', 'pk'],
                'unique_together': {('product', 'name')},
            },
        ),
    ]
