# Generated by Django 6.0.3 on 2026-06-21 20:57

import re

from django.db import migrations, models


def fill_product_modification_params(apps, schema_editor):
    ProductModification = apps.get_model("core", "ProductModification")
    for mod in ProductModification.objects.all().iterator():
        name = (mod.name or "").strip()
        if not name:
            continue
        changed = False
        parts = [p.strip() for p in name.split("|")]
        for part in parts:
            if not part:
                continue
            low = part.lower()
            m = re.search(r"(\d+)\s*мм", low)
            if m and not mod.thickness_mm:
                try:
                    mod.thickness_mm = int(m.group(1))
                    changed = True
                except (TypeError, ValueError):
                    pass
                continue
            if low.startswith("сорт") and not mod.grade:
                grade = part.replace("сорт", "").strip()
                if grade in {"1/2", "2/2", "2/4", "4/4"}:
                    mod.grade = grade
                    changed = True
                continue
            up = part.upper()
            if up in {"Ш1", "Ш2"} and not mod.sanding_sides:
                mod.sanding_sides = up
                changed = True
                continue
            if re.fullmatch(r"P\d{2,3}", up) and not mod.abrasive_grit:
                mod.abrasive_grit = up
                changed = True
        if changed:
            mod.save(
                update_fields=[
                    "thickness_mm",
                    "grade",
                    "sanding_sides",
                    "abrasive_grit",
                ]
            )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0095_productmodification'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodification',
            name='abrasive_grit',
            field=models.CharField(blank=True, max_length=16, verbose_name='Абразив'),
        ),
        migrations.AddField(
            model_name='productmodification',
            name='grade',
            field=models.CharField(blank=True, choices=[('1/2', '1/2'), ('2/2', '2/2'), ('2/4', '2/4'), ('4/4', '4/4')], max_length=8, verbose_name='Сорт'),
        ),
        migrations.AddField(
            model_name='productmodification',
            name='sanding_sides',
            field=models.CharField(blank=True, choices=[('Ш1', 'Ш1'), ('Ш2', 'Ш2')], max_length=8, verbose_name='Шлифование'),
        ),
        migrations.AddField(
            model_name='productmodification',
            name='thickness_mm',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Толщина, мм'),
        ),
        migrations.AlterField(
            model_name='productmodification',
            name='name',
            field=models.CharField(blank=True, help_text='Например: «С гравировкой», «Большая 300x180 мм».', max_length=255, verbose_name='Название модификации'),
        ),
        migrations.RunPython(fill_product_modification_params, migrations.RunPython.noop),
    ]
