# Generated by Django 6.0.3 on 2026-07-04 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0096_productmodification_abrasive_grit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='techcardlaborline',
            name='employee_hourly_rate',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Плановая стоимость часа сотрудника для этого этапа.', max_digits=12, verbose_name='Ставка сотрудника, ₽/ч'),
        ),
        migrations.AddField(
            model_name='techcardlaborline',
            name='employee_minutes',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Сколько минут сотрудник занят на 1 шт.: подготовка макета, настройка станка, укладка материала, контроль, снятие детали, чистка.', max_digits=12, verbose_name='Время сотрудника, мин'),
        ),
        migrations.AlterField(
            model_name='techcardlaborline',
            name='norm_hours',
            field=models.DecimalField(decimal_places=4, default=0, help_text='Время работы станка/этапа на 1 шт. В эту ставку обычно включают амортизацию, электричество и обслуживание оборудования.', max_digits=12, verbose_name='Нормо-часы'),
        ),
    ]
