# Generated by Django 6.0.3 on 2026-07-04 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0097_techcardlaborline_employee_hourly_rate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='techcardlaborline',
            name='employee_hourly_rate',
        ),
    ]
