# Generated by Django 6.0.3 on 2026-07-16 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0098_remove_techcardlaborline_employee_hourly_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='area_m2',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Считается из длины × ширины (мм). Для ед. «лист» — площадь одного листа.', max_digits=14, null=True, verbose_name='Пл. листа, м²'),
        ),
        migrations.AddField(
            model_name='material',
            name='sheet_area_cm2',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=18, null=True, verbose_name='Пл. листа, см²'),
        ),
        migrations.AddField(
            model_name='material',
            name='sheet_area_mm2',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=18, null=True, verbose_name='Пл. листа, мм²'),
        ),
        migrations.AddField(
            model_name='material',
            name='sheet_length_mm',
            field=models.DecimalField(blank=True, decimal_places=0, help_text='Длина листа/заготовки в мм. Вместе с шириной используется для расчёта площади листа.', max_digits=12, null=True, verbose_name='Длина листа, мм'),
        ),
        migrations.AddField(
            model_name='material',
            name='sheet_width_mm',
            field=models.DecimalField(blank=True, decimal_places=0, help_text='Ширина листа/заготовки в мм.', max_digits=12, null=True, verbose_name='Ширина листа, мм'),
        ),
    ]
