# Generated by Django 6.0.3 on 2026-08-17 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0099_material_sheet_dimensions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='area_m2',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Считается автоматически из длины × ширины (мм). Для ед. «лист» — площадь одного листа. Вручную вводить не нужно.', max_digits=14, null=True, verbose_name='Пл. листа, м²'),
        ),
        migrations.AlterField(
            model_name='material',
            name='group',
            field=models.ForeignKey(blank=True, help_text='Раздел справочника (Фанера, Акрил, Металл и т.п.) — для фильтра в списке и в меню склада. Можно не заполнять. Новую группу добавляют кнопкой «+» рядом с полем.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materials', to='core.materialgroup', verbose_name='Группа'),
        ),
        migrations.AlterField(
            model_name='material',
            name='material_type',
            field=models.CharField(blank=True, help_text='Короткий тип для поиска и фильтра, не для цены. Например: ФК, ФСФ, акрил, сталь. Можно оставить пустым.', max_length=100, verbose_name='Тип материала'),
        ),
        migrations.AlterField(
            model_name='material',
            name='name',
            field=models.CharField(help_text='Как материал будет называться в справочнике, в техкарте и в приёмке. Пишите так, чтобы его было легко найти, например: «Фанера ФК 1525×1525×6».', max_length=255, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='material',
            name='photo',
            field=models.ImageField(blank=True, help_text='Необязательное фото материала. Показывается в списке и в карточке. На остаток и цены не влияет.', null=True, upload_to='materials/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='material',
            name='sheet_length_mm',
            field=models.DecimalField(blank=True, decimal_places=0, help_text='Длина листа или заготовки в миллиметрах (целое число). Вместе с шириной считает площадь листа. Если материал не листовой — можно не заполнять.', max_digits=12, null=True, verbose_name='Длина листа, мм'),
        ),
        migrations.AlterField(
            model_name='material',
            name='sheet_width_mm',
            field=models.DecimalField(blank=True, decimal_places=0, help_text='Ширина листа или заготовки в миллиметрах (целое число). Вместе с длиной считает площадь листа.', max_digits=12, null=True, verbose_name='Ширина листа, мм'),
        ),
        migrations.AlterField(
            model_name='material',
            name='thickness_mm',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Толщина листа в миллиметрах. На площадь не влияет — нужна, чтобы отличить позиции (6, 10, 18 мм) и для номенклатуры. Можно не заполнять.', max_digits=8, null=True, verbose_name='Толщина (мм)'),
        ),
        migrations.AlterField(
            model_name='material',
            name='unit',
            field=models.CharField(help_text='В каких единицах ведёте остаток и расход: лист, м², м, кг. Для листовых обычно «лист»: тогда площадь одного листа считается из длины и ширины.', max_length=50, verbose_name='Ед. измерения'),
        ),
    ]
