# Generated by Django 6.0.3 on 2026-08-17 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0100_material_field_help_texts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='area_m2',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Считается автоматически из длины × ширины (мм). Для ед. «лист» — площадь одного листа.', max_digits=14, null=True, verbose_name='Пл. листа, м²'),
        ),
    ]
