# Generated by Django 6.0.3 on 2026-08-17 11:50

import django.db.models.deletion
from django.db import migrations, models


PLYWOOD_TYPES = (
    "ФК",
    "ФСФ",
    "ФОФ",
    "ФБ",
    "ФБС",
    "ФБВ",
    "ФКМ",
    "ламинированная",
)


def seed_group_types(apps, schema_editor):
    Material = apps.get_model("core", "Material")
    MaterialGroup = apps.get_model("core", "MaterialGroup")
    MaterialGroupType = apps.get_model("core", "MaterialGroupType")

    for group in MaterialGroup.objects.all():
        name_n = (group.name or "").casefold().replace("ё", "е")
        if "фанер" in name_n:
            group.has_grade = True
            group.save(update_fields=["has_grade"])
            for i, type_name in enumerate(PLYWOOD_TYPES):
                MaterialGroupType.objects.get_or_create(
                    group=group,
                    name=type_name,
                    defaults={"sort_order": i},
                )
        existing = (
            Material.objects.filter(group=group)
            .exclude(material_type="")
            .values_list("material_type", flat=True)
            .distinct()
        )
        start = MaterialGroupType.objects.filter(group=group).count()
        for j, type_name in enumerate(existing):
            label = (type_name or "").strip()
            if not label:
                continue
            MaterialGroupType.objects.get_or_create(
                group=group,
                name=label[:100],
                defaults={"sort_order": start + j + 10},
            )


def unseed_group_types(apps, schema_editor):
    MaterialGroup = apps.get_model("core", "MaterialGroup")
    MaterialGroupType = apps.get_model("core", "MaterialGroupType")
    MaterialGroupType.objects.all().delete()
    MaterialGroup.objects.filter(has_grade=True).update(has_grade=False)


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0101_material_area_help_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="material",
            name="grade",
            field=models.CharField(
                blank=True,
                help_text="Для фанеры: сорт листа по ГОСТ, например 1/2, 2/2, 3/4. Поле показывается, если у группы включено «Указывать сорт».",
                max_length=20,
                verbose_name="Сорт",
            ),
        ),
        migrations.AddField(
            model_name="materialgroup",
            name="has_grade",
            field=models.BooleanField(
                default=False,
                help_text="Включите для фанеры: в карточке материала появится поле «Сорт» (1/2, 2/2, 3/4…).",
                verbose_name="Указывать сорт",
            ),
        ),
        migrations.AlterField(
            model_name="material",
            name="material_type",
            field=models.CharField(
                blank=True,
                help_text="Короткий тип для поиска и фильтра, не для цены. Например: ФК, ФСФ, акрил, сталь. Список типов зависит от выбранной группы. Можно оставить пустым.",
                max_length=100,
                verbose_name="Тип материала",
            ),
        ),
        migrations.CreateModel(
            name="MaterialGroupType",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100, verbose_name="Тип")),
                ("sort_order", models.PositiveSmallIntegerField(default=0, verbose_name="Порядок")),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="type_choices",
                        to="core.materialgroup",
                        verbose_name="Группа",
                    ),
                ),
            ],
            options={
                "verbose_name": "Тип в группе",
                "verbose_name_plural": "Типы в группе",
                "ordering": ["sort_order", "name"],
                "constraints": [
                    models.UniqueConstraint(fields=("group", "name"), name="uniq_material_group_type_name")
                ],
            },
        ),
        migrations.RunPython(seed_group_types, unseed_group_types),
    ]
