# Generated by Django 6.0.3 on 2026-08-17 12:00

from django.db import migrations, models


PACKAGING_TYPES = (
    "плёнка",
    "скотч",
    "короб",
    "пакет",
    "бумага",
    "пупырка",
)


def seed_packaging_group(apps, schema_editor):
    MaterialGroup = apps.get_model("core", "MaterialGroup")
    MaterialGroupType = apps.get_model("core", "MaterialGroupType")

    group = None
    for existing in MaterialGroup.objects.all():
        name_n = (existing.name or "").casefold().replace("ё", "е")
        if "упаков" in name_n:
            group = existing
            break
    if group is None:
        group = MaterialGroup.objects.create(name="Упаковка", has_grade=False, has_sheet_size=False)
    else:
        group.has_grade = False
        group.has_sheet_size = False
        group.save(update_fields=["has_grade", "has_sheet_size"])

    for i, type_name in enumerate(PACKAGING_TYPES):
        MaterialGroupType.objects.get_or_create(
            group=group,
            name=type_name,
            defaults={"sort_order": i},
        )


def unseed_packaging_group(apps, schema_editor):
    MaterialGroup = apps.get_model("core", "MaterialGroup")
    for group in MaterialGroup.objects.all():
        name_n = (group.name or "").casefold().replace("ё", "е")
        if "упаков" in name_n:
            group.has_sheet_size = True
            group.save(update_fields=["has_sheet_size"])


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0102_material_grade_and_group_types"),
    ]

    operations = [
        migrations.AddField(
            model_name="materialgroup",
            name="has_sheet_size",
            field=models.BooleanField(
                default=True,
                help_text="Длина, ширина, толщина и площадь в карточке материала. Снимите для упаковки — эти поля не нужны.",
                verbose_name="Размеры листа",
            ),
        ),
        migrations.RunPython(seed_packaging_group, unseed_packaging_group),
    ]
