# Generated by Django 6.0.3 on 2026-08-17 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0111_material_abrasive_spec'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='brand',
            field=models.CharField(blank=True, help_text='Марка с полки. Для морилки и абразива участвует в наименовании карточки.', max_length=100, verbose_name='Бренд'),
        ),
        migrations.AlterField(
            model_name='materialgroup',
            name='has_brand',
            field=models.BooleanField(default=False, help_text='Включите для покрытий и абразивов: в карточке появится список брендов.', verbose_name='Указывать бренд'),
        ),
        migrations.AlterField(
            model_name='materialgroup',
            name='has_sheet_size',
            field=models.BooleanField(default=True, help_text='Длина, ширина, толщина и площадь в карточке материала. Снимите для упаковки и абразивов — эти поля не нужны.', verbose_name='Размеры листа'),
        ),
    ]
