# Generated by Django 6.0.3 on 2026-08-17 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0112_abrasive_help_texts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='brand',
            field=models.CharField(blank=True, help_text='Для морилки и абразива участвует в наименовании карточки.', max_length=100, verbose_name='Бренд'),
        ),
    ]
