# Generated by Django 6.0.3 on 2026-08-19

import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0127_remove_semifinished_warehouse"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AdminInvite",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "email",
                    models.EmailField(db_index=True, verbose_name="E-mail"),
                ),
                (
                    "token",
                    models.CharField(
                        default=core.models._admin_invite_token,
                        max_length=64,
                        unique=True,
                        verbose_name="Токен приглашения",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("staff", "Сотрудник"), ("superuser", "Суперпользователь")],
                        default="staff",
                        max_length=20,
                        verbose_name="Роль",
                    ),
                ),
                (
                    "sent_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Дата отправки"),
                ),
                (
                    "accepted_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Дата принятия"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Дата создания")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Дата изменения")),
                (
                    "inviter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="admin_invites_sent",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Кем приглашён",
                    ),
                ),
            ],
            options={
                "verbose_name": "Приглашение в админку",
                "verbose_name_plural": "Приглашения в админку",
            },
        ),
    ]

