# Generated by Django 6.0.3 on 2026-08-19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0129_user_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="middle_name",
            field=models.CharField(blank=True, max_length=150, verbose_name="Отчество"),
        ),
    ]

