# Generated by Django 6.0.3 on 2026-08-21 11:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0130_user_profile_middle_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('login', 'Вход'), ('profile_update', 'Изменение профиля'), ('impersonate_start', 'Включение замещения'), ('impersonate_stop', 'Выключение замещения')], max_length=64, verbose_name='Действие')),
                ('detail', models.TextField(blank=True, verbose_name='Детали')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Когда')),
            ],
            options={
                'verbose_name': 'Запись журнала действий',
                'verbose_name_plural': 'Журнал действий пользователей',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='admininvite',
            index=models.Index(fields=['email'], name='core_admini_email_e7c73a_idx'),
        ),
        migrations.AddField(
            model_name='useractionlog',
            name='related_employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='action_logs', to='core.employee', verbose_name='Связанный сотрудник'),
        ),
        migrations.AddField(
            model_name='useractionlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='action_logs', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
