# Generated by Django 6.0.3 on 2026-08-21 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0131_user_action_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionrequest',
            name='draft_quote_note',
            field=models.CharField(blank=True, max_length=500, verbose_name='Пояснение к ориентиру'),
        ),
        migrations.AddField(
            model_name='productionrequest',
            name='draft_quoted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Ориентир посчитан'),
        ),
        migrations.AddField(
            model_name='productionrequest',
            name='draft_total_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Ориентир суммы, ₽'),
        ),
        migrations.AddField(
            model_name='productionrequest',
            name='draft_unit_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Ориентир цены за 1 шт., ₽'),
        ),
        migrations.AddField(
            model_name='productionrequest',
            name='engraving_text',
            field=models.CharField(blank=True, max_length=500, verbose_name='Текст гравировки'),
        ),
        migrations.AddField(
            model_name='productionrequest',
            name='layout_cut_length_m',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='Длина реза, м'),
        ),
        migrations.AddField(
            model_name='productionrequest',
            name='layout_engrave_length_m',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='Длина гравировки, м'),
        ),
        migrations.AddField(
            model_name='productionrequest',
            name='layout_metrics_note',
            field=models.CharField(blank=True, max_length=500, verbose_name='Заметка по разбору макета'),
        ),
        migrations.AddField(
            model_name='productionrequest',
            name='layout_metrics_status',
            field=models.CharField(blank=True, choices=[('', 'Нет'), ('ok', 'Посчитано'), ('unsupported', 'Формат без авторасчёта'), ('error', 'Ошибка разбора')], default='', max_length=20, verbose_name='Статус авторасчёта длин'),
        ),
        migrations.AddField(
            model_name='productionrequest',
            name='logo_file',
            field=models.FileField(blank=True, null=True, upload_to='production_requests/logos/', verbose_name='Логотип / изображение для гравировки'),
        ),
        migrations.AddField(
            model_name='productionrequest',
            name='order_mode',
            field=models.CharField(choices=[('catalog', 'Из каталога (можно надпись/лого)'), ('custom', 'Индивидуальный макет (DXF)')], default='catalog', max_length=20, verbose_name='Режим заказа'),
        ),
    ]
