# Generated by Django 6.0.3 on 2026-06-21 19:30

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0093_expenseledgerentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialBatchProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Движение по материалу',
                'verbose_name_plural': 'Движения по материалам',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.materialbatch',),
        ),
        migrations.CreateModel(
            name='MaterialStockProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Остаток материала на складе',
                'verbose_name_plural': 'Остатки материалов на складах',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.materialstock',),
        ),
        migrations.CreateModel(
            name='ProductStockProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Остаток продукции на складе',
                'verbose_name_plural': 'Остатки продукции на складах',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.productstock',),
        ),
        migrations.CreateModel(
            name='WarehouseProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Склад',
                'verbose_name_plural': 'Склады',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.warehouse',),
        ),
    ]
