"""
Django settings for laser_erp project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get(
    "DJANGO_SECRET_KEY",
    "django-insecure-local-dev-key-change-me",
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["127.0.0.1", "localhost", "*"]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.forms',
    'core.apps.CoreConfig',
    'procurement.apps.ProcurementConfig',
    'warehouse.apps.WarehouseConfig',
    'production.apps.ProductionConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'laser_erp.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'core.context_processors.admin_product_groups',
                'core.context_processors.admin_warehouse_nav',
                'core.context_processors.storefront_cart_meta',
                'core.context_processors.storefront_user_role',
            ],
        },
    },
]

WSGI_APPLICATION = 'laser_erp.wsgi.application'

# Чтобы шаблоны виджетов из templates/ (русские подписи файла) перекрывали встроенные Django.
FORM_RENDERER = "django.forms.renderers.TemplatesSetting"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'ru'

TIME_ZONE = 'Europe/Moscow'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Media files (user uploads)
MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

# API ФНС (api-fns.ru) — поиск контрагентов по ИНН (ЕГРЮЛ/ЕГРИП)
# Бесплатный ключ: https://api-fns.ru/
FNS_API_KEY = os.environ.get("FNS_API_KEY", "")

# Логирование ошибок (трассировка 500 пишется в debug.log)
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {
        "file": {
            "level": "ERROR",
            "class": "logging.FileHandler",
            "filename": BASE_DIR / "debug.log",
            "encoding": "utf-8",
        },
        "console": {
            "level": "ERROR",
            "class": "logging.StreamHandler",
        },
    },
    "loggers": {
        "django.request": {
            "handlers": ["file", "console"],
            "level": "ERROR",
            "propagate": False,
        },
    },
}

# Ориентир котировки заявки на производство (₽ за погонный метр / персонализация)
QUOTE_DEFAULT_CUT_RATE_PER_M = os.environ.get("QUOTE_DEFAULT_CUT_RATE_PER_M", "15")
QUOTE_DEFAULT_ENGRAVE_RATE_PER_M = os.environ.get("QUOTE_DEFAULT_ENGRAVE_RATE_PER_M", "8")
QUOTE_PERSONALIZATION_FEE = os.environ.get("QUOTE_PERSONALIZATION_FEE", "250")

# Безопасность загрузки макетов (клиентский запрос на производство)
UPLOAD_SECURITY = {
    "max_size_mb": int(os.environ.get("UPLOAD_MAX_SIZE_MB", "20")),
    "allowed_extensions": {
        ".pdf",
        ".cdr",
        ".ai",
        ".eps",
        ".svg",
        ".dxf",
        ".dwg",
        ".zip",
        ".rar",
        ".7z",
        ".png",
        ".jpg",
        ".jpeg",
        ".webp",
    },
    "allowed_mime_types": {
        "application/pdf",
        "application/postscript",
        "application/zip",
        "application/x-zip-compressed",
        "application/x-rar-compressed",
        "application/octet-stream",
        "image/png",
        "image/jpeg",
        "image/webp",
        "image/svg+xml",
    },
}

# Антивирусная проверка через ClamAV.
# Включение через переменную окружения: CLAMAV_ENABLED=1
CLAMAV_SECURITY = {
    "enabled": os.environ.get("CLAMAV_ENABLED", "0") == "1",
    "strict_mode": os.environ.get("CLAMAV_STRICT_MODE", "1") == "1",
    "executable": os.environ.get("CLAMAV_EXECUTABLE", "clamscan"),
    "timeout_seconds": int(os.environ.get("CLAMAV_TIMEOUT_SECONDS", "45")),
}

# OCR распознавание счетов поставщика по фото/PDF.
# Включается через INVOICE_OCR_ENABLED=1 и установленный tesseract.
INVOICE_OCR = {
    "enabled": os.environ.get("INVOICE_OCR_ENABLED", "0") == "1",
    "tesseract_cmd": os.environ.get("INVOICE_OCR_TESSERACT_CMD", "tesseract"),
    "timeout_seconds": int(os.environ.get("INVOICE_OCR_TIMEOUT_SECONDS", "40")),
}

# Авторизация storefront: используем кастомный путь входа.
LOGIN_URL = "/account/login/"

# Почта (приглашения в админку, подтверждение email).
# Сейчас приглашения передаются ссылкой из админки; SMTP опционален.
PUBLIC_SITE_URL = os.environ.get("PUBLIC_SITE_URL", "").strip()
EMAIL_HOST = os.environ.get("EMAIL_HOST", "").strip()
EMAIL_PORT = int(os.environ.get("EMAIL_PORT", "587") or "587")
EMAIL_HOST_USER = os.environ.get("EMAIL_HOST_USER", "").strip()
EMAIL_HOST_PASSWORD = os.environ.get("EMAIL_HOST_PASSWORD", "").strip()
_email_use_tls = os.environ.get("EMAIL_USE_TLS", "").strip().lower()
_email_use_ssl = os.environ.get("EMAIL_USE_SSL", "").strip().lower()
if _email_use_ssl in ("1", "true", "yes"):
    EMAIL_USE_SSL = True
    EMAIL_USE_TLS = False
elif _email_use_tls in ("1", "true", "yes"):
    EMAIL_USE_TLS = True
    EMAIL_USE_SSL = False
else:
    # Яндекс/465 → SSL; иначе по умолчанию STARTTLS на 587.
    EMAIL_USE_SSL = EMAIL_PORT == 465
    EMAIL_USE_TLS = not EMAIL_USE_SSL and EMAIL_PORT in (25, 587)
DEFAULT_FROM_EMAIL = (
    os.environ.get("DEFAULT_FROM_EMAIL", "").strip()
    or EMAIL_HOST_USER
    or "noreply@localhost"
)
SERVER_EMAIL = DEFAULT_FROM_EMAIL
EMAIL_TIMEOUT = int(os.environ.get("EMAIL_TIMEOUT", "20") or "20")

_email_backend = os.environ.get("EMAIL_BACKEND", "").strip()
if _email_backend:
    EMAIL_BACKEND = _email_backend
elif DEBUG and not (EMAIL_HOST and EMAIL_HOST_USER and EMAIL_HOST_PASSWORD):
    EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"
elif EMAIL_HOST and EMAIL_HOST_USER and EMAIL_HOST_PASSWORD:
    EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
else:
    # Без SMTP не притворяемся, что письма уходят.
    EMAIL_BACKEND = "django.core.mail.backends.dummy.EmailBackend"
