# Generated by Django 6.0.3 on 2026-03-29 08:54

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0063_product_kind_material_choice'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseManagementProduct',
            fields=[
            ],
            options={
                'verbose_name': 'Позиция (управление закупками)',
                'verbose_name_plural': 'Управление закупками',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.product',),
        ),
        migrations.CreateModel(
            name='GoodsReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=32, unique=True, verbose_name='Номер приёмки')),
                ('received_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата и время приёмки')),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Можно пересчитать из строк при сохранении', max_digits=14, verbose_name='Сумма (общая)')),
                ('paid_amount', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='Оплачено')),
                ('incoming_document_date', models.DateField(blank=True, help_text='Дата входящего документа поставщика', null=True, verbose_name='Входящая дата')),
                ('incoming_number', models.CharField(blank=True, max_length=100, verbose_name='Входящий номер')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('posted', 'Проведён'), ('cancelled', 'Отменён')], default='draft', max_length=20, verbose_name='Статус')),
                ('is_sent', models.BooleanField(default=False, verbose_name='Отправлено')),
                ('is_printed', models.BooleanField(default=False, verbose_name='Напечатано')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('our_organization', models.ForeignKey(blank=True, help_text='От какой своей организации оформлена приёмка', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goods_receipts_as_buyer', to='core.organization', verbose_name='Организация')),
                ('supplier', models.ForeignKey(help_text='У кого заказывали', on_delete=django.db.models.deletion.PROTECT, related_name='goods_receipts_as_supplier', to='core.organization', verbose_name='Контрагент')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='goods_receipts', to='core.warehouse', verbose_name='Склад')),
            ],
            options={
                'verbose_name': 'Приёмка',
                'verbose_name_plural': 'Приёмка',
                'ordering': ['-received_at', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='GoodsReceiptLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=14, verbose_name='Количество')),
                ('unit_price', models.DecimalField(decimal_places=4, max_digits=14, verbose_name='Цена за ед.')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Сумма строки')),
                ('goods_receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='procurement.goodsreceipt', verbose_name='Приёмка')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='goods_receipt_lines', to='core.material', verbose_name='Материал')),
            ],
            options={
                'verbose_name': 'Строка приёмки',
                'verbose_name_plural': 'Строки приёмки',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='ReceivedVatInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=32, unique=True, verbose_name='Номер')),
                ('invoice_date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата')),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='Сумма')),
                ('status', models.CharField(blank=True, default='draft', max_length=20, verbose_name='Статус')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('our_organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_vat_invoices_as_buyer', to='core.organization', verbose_name='Наша организация')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='received_vat_invoices', to='core.organization', verbose_name='Поставщик')),
            ],
            options={
                'verbose_name': 'Счёт-фактура полученный',
                'verbose_name_plural': 'Счета-фактуры полученные',
                'ordering': ['-invoice_date', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='SupplierInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=32, unique=True, verbose_name='Номер')),
                ('invoice_date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата счёта')),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='Сумма')),
                ('status', models.CharField(blank=True, default='draft', max_length=20, verbose_name='Статус')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('our_organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier_invoices_as_buyer', to='core.organization', verbose_name='Наша организация')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supplier_invoices', to='core.organization', verbose_name='Поставщик')),
            ],
            options={
                'verbose_name': 'Счёт поставщика',
                'verbose_name_plural': 'Счета поставщиков',
                'ordering': ['-invoice_date', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='SupplierPurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=32, unique=True, verbose_name='Номер')),
                ('ordered_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата заказа')),
                ('status', models.CharField(blank=True, default='draft', max_length=20, verbose_name='Статус')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('our_organization', models.ForeignKey(blank=True, help_text='От имени какой своей организации оформлен заказ', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_orders_as_buyer', to='core.organization', verbose_name='Наша организация')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders_as_supplier', to='core.organization', verbose_name='Поставщик')),
            ],
            options={
                'verbose_name': 'Заказ поставщику',
                'verbose_name_plural': 'Заказы поставщикам',
                'ordering': ['-ordered_at', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='SupplierReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=32, unique=True, verbose_name='Номер')),
                ('returned_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата возврата')),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='Сумма')),
                ('status', models.CharField(blank=True, default='draft', max_length=20, verbose_name='Статус')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supplier_returns', to='core.organization', verbose_name='Поставщик')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supplier_returns', to='core.warehouse', verbose_name='Склад')),
            ],
            options={
                'verbose_name': 'Возврат поставщику',
                'verbose_name_plural': 'Возвраты поставщикам',
                'ordering': ['-returned_at', '-pk'],
            },
        ),
    ]
