# Generated by Django 6.0.3 on 2026-03-29 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodsreceipt',
            name='posted_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Проведена'),
        ),
        migrations.AlterField(
            model_name='goodsreceipt',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('posted', 'Проведён'), ('cancelled', 'Отменён')], default='draft', help_text='«Проведён» — создаются движения по материалам (приёмка) и приход на склад. Отменить проведение нельзя.', max_length=20, verbose_name='Статус'),
        ),
    ]
