# Generated by Django 6.0.3 on 2026-03-29 09:44

import django.db.models.deletion
from django.db import migrations, models


def _normalize_po_status(apps, schema_editor):
    SupplierPurchaseOrder = apps.get_model("procurement", "SupplierPurchaseOrder")
    SupplierPurchaseOrder.objects.filter(status="").update(status="draft")


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0063_product_kind_material_choice'),
        ('procurement', '0002_goodsreceipt_posted_at'),
    ]

    operations = [
        migrations.RunPython(_normalize_po_status, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='supplierpurchaseorder',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('sent', 'Отправлен поставщику'), ('confirmed', 'Подтверждён'), ('closed', 'Закрыт'), ('cancelled', 'Отменён')], default='draft', help_text='В «Ожидание» по товару входят строки заказов в статусах «Отправлен» и «Подтверждён».', max_length=20, verbose_name='Статус'),
        ),
        migrations.CreateModel(
            name='SupplierPurchaseOrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=14, verbose_name='Количество')),
                ('unit_price', models.DecimalField(blank=True, decimal_places=4, help_text='Ожидаемая цена закупки (необязательно)', max_digits=14, null=True, verbose_name='Цена за ед.')),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='supplier_order_lines', to='core.material', verbose_name='Материал')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='supplier_order_lines', to='core.product', verbose_name='Товар')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='procurement.supplierpurchaseorder', verbose_name='Заказ поставщику')),
            ],
            options={
                'verbose_name': 'Строка заказа поставщику',
                'verbose_name_plural': 'Строки заказа поставщику',
                'ordering': ['pk'],
            },
        ),
    ]
