# Generated by Django 6.0.3 on 2026-03-29 10:04

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0063_product_kind_material_choice'),
        ('procurement', '0004_goodsreceipt_contract_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodsreceiptline',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='goods_receipt_lines', to='core.product', verbose_name='Товар (готовая продукция)'),
        ),
        migrations.AddField(
            model_name='goodsreceiptline',
            name='supplier_order_line',
            field=models.ForeignKey(blank=True, help_text='Если указано — при проведении увеличится «Получено» по заказу (поставщик и номенклатура должны совпадать).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goods_receipt_lines', to='procurement.supplierpurchaseorderline', verbose_name='Строка заказа поставщику'),
        ),
        migrations.AddField(
            model_name='supplierpurchaseorderline',
            name='quantity_received',
            field=models.DecimalField(decimal_places=4, default=Decimal('0'), help_text='Накапливается при проведении приёмок, привязанных к этой строке заказа.', max_digits=14, verbose_name='Получено'),
        ),
        migrations.AlterField(
            model_name='goodsreceipt',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('posted', 'Проведён'), ('cancelled', 'Отменён')], default='draft', help_text='«Проведён» — приход на склад: материалы (движение + остаток материалов) или готовая продукция (остаток продукции). При указании строки заказа поставщику увеличивается «Получено» по заказу. Отменить проведение нельзя.', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='goodsreceiptline',
            name='material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='goods_receipt_lines', to='core.material', verbose_name='Материал'),
        ),
    ]
