# Generated by Django 6.0.3 on 2026-05-11 19:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0088_organization_bank_account_organization_bank_bik_and_more'),
        ('procurement', '0005_goods_receipt_po_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodsreceipt',
            name='contract_ref',
            field=models.ForeignKey(blank=True, help_text='Действующий договор с контрагентом. Для проведения приёмки обязателен.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goods_receipts', to='core.contract', verbose_name='Договор (карточка)'),
        ),
        migrations.AddField(
            model_name='supplierinvoice',
            name='invoice_file',
            field=models.FileField(blank=True, upload_to='supplier_invoices/raw/', verbose_name='Файл счёта (фото/PDF)'),
        ),
        migrations.AddField(
            model_name='supplierinvoice',
            name='ocr_data',
            field=models.JSONField(blank=True, default=dict, verbose_name='Распознанные поля'),
        ),
        migrations.AddField(
            model_name='supplierinvoice',
            name='ocr_result_text',
            field=models.TextField(blank=True, verbose_name='Результат OCR'),
        ),
        migrations.AddField(
            model_name='supplierinvoice',
            name='ocr_reviewed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Подтверждено OCR'),
        ),
        migrations.AddField(
            model_name='supplierinvoice',
            name='ocr_status',
            field=models.CharField(choices=[('pending', 'Ожидает распознавания'), ('review', 'Требует подтверждения'), ('applied', 'Подтверждено'), ('failed', 'Ошибка распознавания')], default='pending', max_length=20, verbose_name='Статус OCR'),
        ),
    ]
