# Generated by Django 6.0.3 on 2026-05-11 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0006_goodsreceipt_contract_ref_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierinvoice',
            name='expense_category',
            field=models.CharField(blank=True, choices=[('materials', 'Материалы/сырье'), ('logistics', 'Логистика/доставка'), ('services', 'Услуги'), ('rent', 'Аренда'), ('utilities', 'Коммунальные услуги'), ('marketing', 'Маркетинг/реклама'), ('it', 'IT/связь/ПО'), ('equipment', 'Оборудование'), ('other', 'Прочее')], default='', max_length=32, verbose_name='Категория расходов'),
        ),
    ]
