# Generated by Django 6.0.3 on 2026-05-11 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0007_supplierinvoice_expense_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierInvoiceCategoryMemory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('normalized_name', models.CharField(max_length=255, unique=True, verbose_name='Нормализованное наименование')),
                ('source_name', models.CharField(max_length=255, verbose_name='Наименование (как в счёте)')),
                ('category', models.CharField(choices=[('materials', 'Материалы/сырье'), ('logistics', 'Логистика/доставка'), ('services', 'Услуги'), ('rent', 'Аренда'), ('utilities', 'Коммунальные услуги'), ('marketing', 'Маркетинг/реклама'), ('it', 'IT/связь/ПО'), ('equipment', 'Оборудование'), ('other', 'Прочее')], max_length=32, verbose_name='Категория расходов')),
                ('confirmations', models.PositiveIntegerField(default=1, verbose_name='Подтверждений')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Память категории по счёту',
                'verbose_name_plural': 'Память категорий по счетам',
                'ordering': ['-updated_at', '-pk'],
            },
        ),
    ]
