# Generated by Django 6.0.3 on 2026-05-11 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0008_supplierinvoicecategorymemory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplierinvoice',
            name='status',
            field=models.CharField(blank=True, choices=[('draft', 'Черновик'), ('approved', 'Утверждён'), ('paid', 'Оплачен'), ('cancelled', 'Отменён')], default='draft', max_length=20, verbose_name='Статус'),
        ),
    ]
