# Generated by Django 6.0.3 on 2026-05-24 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0009_alter_supplierinvoice_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplierinvoice',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Назначение платежа'),
        ),
    ]
