# Generated by Django 6.0.3 on 2026-05-24 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0010_alter_supplierinvoice_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierinvoice',
            name='expense_subcategory',
            field=models.CharField(blank=True, choices=[('rent_operating_services', 'Эксплуатационные услуги')], default='', max_length=64, verbose_name='Подкатегория расходов'),
        ),
    ]
